import Sel4Lean
import Sel4Lean.Spec.Gen.Mod.API_Failures
import Sel4Lean.Spec.Gen.Mod.API_InvocationLabels
import Sel4Lean.Spec.Gen.Mod.API_Types
import Sel4Lean.Spec.Gen.Mod.API_Types_RISCV64
import Sel4Lean.Spec.Gen.Mod.Kernel_Thread
import Sel4Lean.Spec.Gen.Mod.Kernel_VSpace
import Sel4Lean.Spec.Gen.Mod.Kernel_VSpace_RISCV64
import Sel4Lean.Spec.Gen.Mod.Machine_Hardware_RISCV64
import Sel4Lean.Spec.Gen.Mod.Object_CNode
import Sel4Lean.Spec.Gen.Mod.Object_Endpoint
import Sel4Lean.Spec.Gen.Mod.Object_Interrupt
import Sel4Lean.Spec.Gen.Mod.Object_Notification
import Sel4Lean.Spec.Gen.Mod.Object_ObjectType
import Sel4Lean.Spec.Gen.Mod.Object_ObjectType_RISCV64
import Sel4Lean.Spec.Gen.Mod.Object_Structures
import Sel4Lean.Spec.Gen.Mod.Object_Structures_RISCV64
import Sel4Lean.Spec.Gen.Mod.Object_TCB
import Sel4Lean.Spec.Gen.Mod.Object_TCB_RISCV64
import Sel4Lean.Spec.Gen.Mod.Object_Untyped
open Sel4Lean.Spec
set_option maxRecDepth 4000

class ShowS (α : Type) where
  showS : α → String
export ShowS (showS)
mutual
partial def show_ASID : _root_.Sel4Lean.Spec.ASID → String
  | .ASID a0 => (fun (x : BitVec 64) => toString x.toNat) a0

partial def show_CapRights : _root_.Sel4Lean.Spec.CapRights → String
  | .CapRights a0 a1 a2 a3 => "(CapRights" ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a0 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a1 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a2 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a3 ++ ")"

partial def show_RISCV64_IRQ : _root_.Sel4Lean.Spec.RISCV64.IRQ → String
  | .IRQ a0 => (fun (x : BitVec 32) => toString x.toNat) a0

partial def show_IRQ : _root_.Sel4Lean.Spec.IRQ → String
  | .IRQ a0 => show_RISCV64_IRQ a0

partial def show_ZombieType : _root_.Sel4Lean.Spec.ZombieType → String
  | .ZombieTCB => "ZombieTCB"
  | .ZombieCNode a0 => "(ZombieCNode" ++ " " ++ (fun (x : Nat) => toString x) a0 ++ ")"

partial def show_VMRights : _root_.Sel4Lean.Spec.VMRights → String
  | .VMKernelOnly => "VMKernelOnly"
  | .VMReadOnly => "VMReadOnly"
  | .VMReadWrite => "VMReadWrite"

partial def show_VMPageSize : _root_.Sel4Lean.Spec.VMPageSize → String
  | .RISCVSmallPage => "RISCVSmallPage"
  | .RISCVLargePage => "RISCVLargePage"
  | .RISCVHugePage => "RISCVHugePage"

partial def show_VPtr : _root_.Sel4Lean.Spec.VPtr → String
  | .VPtr a0 => (fun (x : BitVec 64) => toString x.toNat) a0

partial def show_ArchCapability : _root_.Sel4Lean.Spec.ArchCapability → String
  | .ASIDControlCap => "ASIDControlCap"
  | .ASIDPoolCap a0 a1 => "(ASIDPoolCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.ASIDPool) => toString x.ptr.toNat) a0 ++ " " ++ show_ASID a1 ++ ")"
  | .FrameCap a0 a1 a2 a3 a4 => "(FrameCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr (BitVec 64)) => toString x.ptr.toNat) a0 ++ " " ++ show_VMRights a1 ++ " " ++ show_VMPageSize a2 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a3 ++ " " ++ (fun (x : Option (_root_.Sel4Lean.Spec.ASID × _root_.Sel4Lean.Spec.VPtr)) => match x with | none => "None" | some v => "(Some " ++ (fun (p : _root_.Sel4Lean.Spec.ASID × _root_.Sel4Lean.Spec.VPtr) => "(Pair " ++ show_ASID p.1 ++ " " ++ show_VPtr p.2 ++ ")") v ++ ")") a4 ++ ")"
  | .PageTableCap a0 a1 => "(PageTableCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.PTE) => toString x.ptr.toNat) a0 ++ " " ++ (fun (x : Option (_root_.Sel4Lean.Spec.ASID × _root_.Sel4Lean.Spec.VPtr)) => match x with | none => "None" | some v => "(Some " ++ (fun (p : _root_.Sel4Lean.Spec.ASID × _root_.Sel4Lean.Spec.VPtr) => "(Pair " ++ show_ASID p.1 ++ " " ++ show_VPtr p.2 ++ ")") v ++ ")") a1 ++ ")"

partial def show_Capability : _root_.Sel4Lean.Spec.Capability → String
  | .ThreadCap a0 => "(ThreadCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.TCB) => toString x.ptr.toNat) a0 ++ ")"
  | .NullCap => "NullCap"
  | .NotificationCap a0 a1 a2 a3 => "(NotificationCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.Notification) => toString x.ptr.toNat) a0 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a1 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a2 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a3 ++ ")"
  | .IRQHandlerCap a0 => "(IRQHandlerCap" ++ " " ++ show_IRQ a0 ++ ")"
  | .EndpointCap a0 a1 a2 a3 a4 a5 => "(EndpointCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.Endpoint) => toString x.ptr.toNat) a0 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a1 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a2 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a3 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a4 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a5 ++ ")"
  | .DomainCap => "DomainCap"
  | .Zombie a0 a1 a2 => "(Zombie" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.CTE) => toString x.ptr.toNat) a0 ++ " " ++ show_ZombieType a1 ++ " " ++ (fun (x : Nat) => toString x) a2 ++ ")"
  | .ArchObjectCap a0 => "(ArchObjectCap" ++ " " ++ show_ArchCapability a0 ++ ")"
  | .ReplyCap a0 a1 a2 => "(ReplyCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.TCB) => toString x.ptr.toNat) a0 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a1 ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a2 ++ ")"
  | .UntypedCap a0 a1 a2 a3 => "(UntypedCap" ++ " " ++ (fun (x : Bool) => if x then "True" else "False") a0 ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr Unit) => toString x.ptr.toNat) a1 ++ " " ++ (fun (x : Nat) => toString x) a2 ++ " " ++ (fun (x : Nat) => toString x) a3 ++ ")"
  | .CNodeCap a0 a1 a2 a3 => "(CNodeCap" ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.CTE) => toString x.ptr.toNat) a0 ++ " " ++ (fun (x : Nat) => toString x) a1 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a2 ++ " " ++ (fun (x : Nat) => toString x) a3 ++ ")"
  | .IRQControlCap => "IRQControlCap"

partial def show_GenInvocationLabels : _root_.Sel4Lean.Spec.GenInvocationLabels → String
  | .InvalidInvocation => "InvalidInvocation"
  | .UntypedRetype => "UntypedRetype"
  | .TCBReadRegisters => "TCBReadRegisters"
  | .TCBWriteRegisters => "TCBWriteRegisters"
  | .TCBCopyRegisters => "TCBCopyRegisters"
  | .TCBConfigure => "TCBConfigure"
  | .TCBSetPriority => "TCBSetPriority"
  | .TCBSetMCPriority => "TCBSetMCPriority"
  | .TCBSetSchedParams => "TCBSetSchedParams"
  | .TCBSetIPCBuffer => "TCBSetIPCBuffer"
  | .TCBSetSpace => "TCBSetSpace"
  | .TCBSuspend => "TCBSuspend"
  | .TCBResume => "TCBResume"
  | .TCBBindNotification => "TCBBindNotification"
  | .TCBUnbindNotification => "TCBUnbindNotification"
  | .TCBSetTLSBase => "TCBSetTLSBase"
  | .TCBSetFlags => "TCBSetFlags"
  | .CNodeRevoke => "CNodeRevoke"
  | .CNodeDelete => "CNodeDelete"
  | .CNodeCancelBadgedSends => "CNodeCancelBadgedSends"
  | .CNodeCopy => "CNodeCopy"
  | .CNodeMint => "CNodeMint"
  | .CNodeMove => "CNodeMove"
  | .CNodeMutate => "CNodeMutate"
  | .CNodeRotate => "CNodeRotate"
  | .CNodeSaveCaller => "CNodeSaveCaller"
  | .IRQIssueIRQHandler => "IRQIssueIRQHandler"
  | .IRQAckIRQ => "IRQAckIRQ"
  | .IRQSetIRQHandler => "IRQSetIRQHandler"
  | .IRQClearIRQHandler => "IRQClearIRQHandler"
  | .DomainSetSet => "DomainSetSet"
  | .DomainScheduleConfigure => "DomainScheduleConfigure"
  | .DomainScheduleSetStart => "DomainScheduleSetStart"

partial def show_ArchInvocationLabel : _root_.Sel4Lean.Spec.ArchInvocationLabel → String
  | .RISCVPageTableMap => "RISCVPageTableMap"
  | .RISCVPageTableUnmap => "RISCVPageTableUnmap"
  | .RISCVPageMap => "RISCVPageMap"
  | .RISCVPageUnmap => "RISCVPageUnmap"
  | .RISCVPageGetAddress => "RISCVPageGetAddress"
  | .RISCVASIDControlMakePool => "RISCVASIDControlMakePool"
  | .RISCVASIDPoolAssign => "RISCVASIDPoolAssign"
  | .RISCVIRQIssueIRQHandler => "RISCVIRQIssueIRQHandler"

partial def show_InvocationLabel : _root_.Sel4Lean.Spec.InvocationLabel → String
  | .GenInvocationLabel a0 => "(GenInvocationLabel" ++ " " ++ show_GenInvocationLabels a0 ++ ")"
  | .ArchInvocationLabel a0 => "(ArchInvocationLabel" ++ " " ++ show_ArchInvocationLabel a0 ++ ")"

partial def show_MessageInfo : _root_.Sel4Lean.Spec.MessageInfo → String
  | .MI a0 a1 a2 a3 => "(MI" ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a0 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a1 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a2 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) a3 ++ ")"

partial def show_APIObjectType : _root_.Sel4Lean.Spec.APIObjectType → String
  | .Untyped => "Untyped"
  | .TCBObject => "TCBObject"
  | .EndpointObject => "EndpointObject"
  | .NotificationObject => "NotificationObject"
  | .CapTableObject => "CapTableObject"

partial def show_ObjectType : _root_.Sel4Lean.Spec.ObjectType → String
  | .APIObjectType a0 => "(APIObjectType" ++ " " ++ show_APIObjectType a0 ++ ")"
  | .HugePageObject => "HugePageObject"
  | .SmallPageObject => "SmallPageObject"
  | .LargePageObject => "LargePageObject"
  | .PageTableObject => "PageTableObject"

partial def show_Region : _root_.Sel4Lean.Spec.Region → String
  | .Region a0 => (fun (p : (Sel4Lean.Exec.PPtr (BitVec 64)) × (Sel4Lean.Exec.PPtr (BitVec 64))) => "(Pair " ++ (fun (x : Sel4Lean.Exec.PPtr (BitVec 64)) => toString x.ptr.toNat) p.1 ++ " " ++ (fun (x : Sel4Lean.Exec.PPtr (BitVec 64)) => toString x.ptr.toNat) p.2 ++ ")") a0

partial def show_VMAttributes : _root_.Sel4Lean.Spec.VMAttributes → String
  | .VMAttributes a0 => (fun (x : Bool) => if x then "True" else "False") a0
end
instance : ShowS (_root_.Sel4Lean.Spec.ASID) := ⟨show_ASID⟩
instance : ShowS (BitVec 64) := ⟨(fun (x : BitVec 64) => toString x.toNat)⟩
instance : ShowS (BitVec 8) := ⟨(fun (x : BitVec 8) => toString x.toNat)⟩
instance : ShowS (Bool) := ⟨(fun (x : Bool) => if x then "True" else "False")⟩
instance : ShowS (_root_.Sel4Lean.Spec.CapRights) := ⟨show_CapRights⟩
instance : ShowS (_root_.Sel4Lean.Spec.Capability) := ⟨show_Capability⟩
instance : ShowS (_root_.Sel4Lean.Spec.GenInvocationLabels) := ⟨show_GenInvocationLabels⟩
instance : ShowS (_root_.Sel4Lean.Spec.InvocationLabel) := ⟨show_InvocationLabel⟩
instance : ShowS (List (BitVec 64)) := ⟨(fun (xs : List (BitVec 64)) => "[" ++ ", ".intercalate (xs.map (fun (x : BitVec 64) => toString x.toNat)) ++ "]")⟩
instance : ShowS (_root_.Sel4Lean.Spec.MessageInfo) := ⟨show_MessageInfo⟩
instance : ShowS (Nat) := ⟨(fun (x : Nat) => toString x)⟩
instance : ShowS (_root_.Sel4Lean.Spec.ObjectType) := ⟨show_ObjectType⟩
instance : ShowS (Option ((BitVec 64) × (BitVec 64))) := ⟨(fun (x : Option ((BitVec 64) × (BitVec 64))) => match x with | none => "None" | some v => "(Some " ++ (fun (p : (BitVec 64) × (BitVec 64)) => "(Pair " ++ (fun (x : BitVec 64) => toString x.toNat) p.1 ++ " " ++ (fun (x : BitVec 64) => toString x.toNat) p.2 ++ ")") v ++ ")")⟩
instance : ShowS (Option _root_.Sel4Lean.Spec.APIObjectType) := ⟨(fun (x : Option _root_.Sel4Lean.Spec.APIObjectType) => match x with | none => "None" | some v => "(Some " ++ show_APIObjectType v ++ ")")⟩
instance : ShowS (Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.PTE) := ⟨(fun (x : Sel4Lean.Exec.PPtr _root_.Sel4Lean.Spec.PTE) => toString x.ptr.toNat)⟩
instance : ShowS (Sel4Lean.Exec.PPtr Unit) := ⟨(fun (x : Sel4Lean.Exec.PPtr Unit) => toString x.ptr.toNat)⟩
instance : ShowS (_root_.Sel4Lean.Spec.Region) := ⟨show_Region⟩
instance : ShowS (_root_.Sel4Lean.Spec.VMAttributes) := ⟨show_VMAttributes⟩
instance : ShowS (_root_.Sel4Lean.Spec.VMRights) := ⟨show_VMRights⟩
instance : ShowS ((BitVec 64)) := ⟨(fun (x : BitVec 64) => toString x.toNat)⟩
instance : ShowS ((BitVec 64) × (List (BitVec 64))) := ⟨(fun (p : (BitVec 64) × (List (BitVec 64))) => "(Pair " ++ (fun (x : BitVec 64) => toString x.toNat) p.1 ++ " " ++ (fun (xs : List (BitVec 64)) => "[" ++ ", ".intercalate (xs.map (fun (x : BitVec 64) => toString x.toNat)) ++ "]") p.2 ++ ")")⟩

#eval IO.println s!"1|{showS (Sel4Lean.Spec.M.API_Failures.msgFromLookupFailure (_root_.Sel4Lean.Spec.LookupFailure.GuardMismatch 3 0 3))}"
#eval IO.println s!"2|{showS (Sel4Lean.Spec.M.API_Failures.msgFromLookupFailure (_root_.Sel4Lean.Spec.LookupFailure.DepthMismatch 12 1))}"
#eval IO.println s!"3|{showS (Sel4Lean.Spec.M.API_Failures.msgFromLookupFailure (_root_.Sel4Lean.Spec.LookupFailure.InvalidRoot))}"
#eval IO.println s!"4|{showS (Sel4Lean.Spec.M.API_Failures.msgFromLookupFailure (_root_.Sel4Lean.Spec.LookupFailure.DepthMismatch 5 31))}"
#eval IO.println s!"5|{showS (Sel4Lean.Spec.M.API_Failures.msgFromLookupFailure (_root_.Sel4Lean.Spec.LookupFailure.DepthMismatch 63 5))}"
#eval IO.println s!"6|{showS (Sel4Lean.Spec.M.API_Failures.msgFromLookupFailure (_root_.Sel4Lean.Spec.LookupFailure.MissingCapability 31))}"
#eval IO.println s!"7|{showS (Sel4Lean.Spec.M.API_Failures.msgFromSyscallError (_root_.Sel4Lean.Spec.SyscallError.InvalidArgument 8))}"
#eval IO.println s!"8|{showS (Sel4Lean.Spec.M.API_Failures.msgFromSyscallError (_root_.Sel4Lean.Spec.SyscallError.DeleteFirst))}"
#eval IO.println s!"9|{showS (Sel4Lean.Spec.M.API_Failures.msgFromSyscallError (_root_.Sel4Lean.Spec.SyscallError.AlignmentError))}"
#eval IO.println s!"10|{showS (Sel4Lean.Spec.M.API_Failures.msgFromSyscallError (_root_.Sel4Lean.Spec.SyscallError.RevokeFirst))}"
#eval IO.println s!"11|{showS (Sel4Lean.Spec.M.API_Failures.msgFromSyscallError (_root_.Sel4Lean.Spec.SyscallError.DeleteFirst))}"
#eval IO.println s!"12|{showS (Sel4Lean.Spec.M.API_Failures.msgFromSyscallError (_root_.Sel4Lean.Spec.SyscallError.InvalidCapability 63))}"
#eval IO.println s!"13|{showS (Sel4Lean.Spec.M.API_InvocationLabels.invocationType 7)}"
#eval IO.println s!"14|{showS (Sel4Lean.Spec.M.API_InvocationLabels.invocationType 18446744073709551615)}"
#eval IO.println s!"15|{showS (Sel4Lean.Spec.M.API_InvocationLabels.invocationType 0)}"
#eval IO.println s!"16|{showS (Sel4Lean.Spec.M.API_InvocationLabels.invocationType 2)}"
#eval IO.println s!"17|{showS (Sel4Lean.Spec.M.API_InvocationLabels.invocationType 0)}"
#eval IO.println s!"18|{showS (Sel4Lean.Spec.M.API_InvocationLabels.invocationType 8837434004073419807)}"
#eval IO.println s!"19|{showS (Sel4Lean.Spec.M.API_InvocationLabels.genInvocationType 2)}"
#eval IO.println s!"20|{showS (Sel4Lean.Spec.M.API_InvocationLabels.genInvocationType 1)}"
#eval IO.println s!"21|{showS (Sel4Lean.Spec.M.API_InvocationLabels.genInvocationType 12491875293972162987)}"
#eval IO.println s!"22|{showS (Sel4Lean.Spec.M.API_InvocationLabels.genInvocationType 9223372036854775808)}"
#eval IO.println s!"23|{showS (Sel4Lean.Spec.M.API_InvocationLabels.genInvocationType 2)}"
#eval IO.println s!"24|{showS (Sel4Lean.Spec.M.API_InvocationLabels.genInvocationType 0)}"
#eval IO.println s!"25|{showS (Sel4Lean.Spec.M.API_Types.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.HugePageObject) 1)}"
#eval IO.println s!"26|{showS (Sel4Lean.Spec.M.API_Types.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.HugePageObject) 2)}"
#eval IO.println s!"27|{showS (Sel4Lean.Spec.M.API_Types.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.PageTableObject) 3)}"
#eval IO.println s!"28|{showS (Sel4Lean.Spec.M.API_Types.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject) 8)}"
#eval IO.println s!"29|{showS (Sel4Lean.Spec.M.API_Types.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.PageTableObject) 31)}"
#eval IO.println s!"30|{showS (Sel4Lean.Spec.M.API_Types.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.PageTableObject) 3)}"
#eval IO.println s!"31|{showS (Sel4Lean.Spec.M.API_Types.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.TCBObject))}"
#eval IO.println s!"32|{showS (Sel4Lean.Spec.M.API_Types.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.TCBObject))}"
#eval IO.println s!"33|{showS (Sel4Lean.Spec.M.API_Types.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.NotificationObject))}"
#eval IO.println s!"34|{showS (Sel4Lean.Spec.M.API_Types.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject))}"
#eval IO.println s!"35|{showS (Sel4Lean.Spec.M.API_Types.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.NotificationObject))}"
#eval IO.println s!"36|{showS (Sel4Lean.Spec.M.API_Types.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject))}"
#eval IO.println s!"37|{showS (Sel4Lean.Spec.M.API_Types.toAPIType (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject)))}"
#eval IO.println s!"38|{showS (Sel4Lean.Spec.M.API_Types.toAPIType (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.EndpointObject)))}"
#eval IO.println s!"39|{showS (Sel4Lean.Spec.M.API_Types.toAPIType (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.NotificationObject)))}"
#eval IO.println s!"40|{showS (Sel4Lean.Spec.M.API_Types.toAPIType (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.Untyped)))}"
#eval IO.println s!"41|{showS (Sel4Lean.Spec.M.API_Types.toAPIType (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject)))}"
#eval IO.println s!"42|{showS (Sel4Lean.Spec.M.API_Types.toAPIType (_root_.Sel4Lean.Spec.ObjectType.PageTableObject))}"
#eval IO.println s!"43|{showS (Sel4Lean.Spec.M.API_Types.isFrameType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"44|{showS (Sel4Lean.Spec.M.API_Types.isFrameType (_root_.Sel4Lean.Spec.ObjectType.LargePageObject))}"
#eval IO.println s!"45|{showS (Sel4Lean.Spec.M.API_Types.isFrameType (_root_.Sel4Lean.Spec.ObjectType.HugePageObject))}"
#eval IO.println s!"46|{showS (Sel4Lean.Spec.M.API_Types.isFrameType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"47|{showS (Sel4Lean.Spec.M.API_Types.isFrameType (_root_.Sel4Lean.Spec.ObjectType.LargePageObject))}"
#eval IO.println s!"48|{showS (Sel4Lean.Spec.M.API_Types.isFrameType (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.EndpointObject)))}"
#eval IO.println s!"49|{showS (Sel4Lean.Spec.M.API_Types.andCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true true true) (_root_.Sel4Lean.Spec.CapRights.CapRights false true true true))}"
#eval IO.println s!"50|{showS (Sel4Lean.Spec.M.API_Types.andCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true false true) (_root_.Sel4Lean.Spec.CapRights.CapRights true true true true))}"
#eval IO.println s!"51|{showS (Sel4Lean.Spec.M.API_Types.andCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true true false) (_root_.Sel4Lean.Spec.CapRights.CapRights true false false true))}"
#eval IO.println s!"52|{showS (Sel4Lean.Spec.M.API_Types.andCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false false true false) (_root_.Sel4Lean.Spec.CapRights.CapRights true false true false))}"
#eval IO.println s!"53|{showS (Sel4Lean.Spec.M.API_Types.andCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false false false false) (_root_.Sel4Lean.Spec.CapRights.CapRights true true false false))}"
#eval IO.println s!"54|{showS (Sel4Lean.Spec.M.API_Types.andCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true false false) (_root_.Sel4Lean.Spec.CapRights.CapRights true true false false))}"
#eval IO.println s!"55|{showS (Sel4Lean.Spec.M.API_Types.rightsFromWord 9223372036854775808)}"
#eval IO.println s!"56|{showS (Sel4Lean.Spec.M.API_Types.rightsFromWord 2872394506345289373)}"
#eval IO.println s!"57|{showS (Sel4Lean.Spec.M.API_Types.rightsFromWord 0)}"
#eval IO.println s!"58|{showS (Sel4Lean.Spec.M.API_Types.rightsFromWord 2)}"
#eval IO.println s!"59|{showS (Sel4Lean.Spec.M.API_Types.rightsFromWord 9223372036854775808)}"
#eval IO.println s!"60|{showS (Sel4Lean.Spec.M.API_Types.rightsFromWord 7)}"
#eval IO.println s!"61|{showS (Sel4Lean.Spec.M.API_Types.wordFromRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true true true))}"
#eval IO.println s!"62|{showS (Sel4Lean.Spec.M.API_Types.wordFromRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true true true))}"
#eval IO.println s!"63|{showS (Sel4Lean.Spec.M.API_Types.wordFromRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true false true))}"
#eval IO.println s!"64|{showS (Sel4Lean.Spec.M.API_Types.wordFromRights (_root_.Sel4Lean.Spec.CapRights.CapRights false false true true))}"
#eval IO.println s!"65|{showS (Sel4Lean.Spec.M.API_Types.wordFromRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true true false))}"
#eval IO.println s!"66|{showS (Sel4Lean.Spec.M.API_Types.wordFromRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true false false))}"
#eval IO.println s!"67|{showS (Sel4Lean.Spec.M.API_Types.messageInfoFromWord 18446744073709551615)}"
#eval IO.println s!"68|{showS (Sel4Lean.Spec.M.API_Types.messageInfoFromWord 8557869880737888495)}"
#eval IO.println s!"69|{showS (Sel4Lean.Spec.M.API_Types.messageInfoFromWord 15771961084932977449)}"
#eval IO.println s!"70|{showS (Sel4Lean.Spec.M.API_Types.messageInfoFromWord 2)}"
#eval IO.println s!"71|{showS (Sel4Lean.Spec.M.API_Types.messageInfoFromWord 18446744073709551615)}"
#eval IO.println s!"72|{showS (Sel4Lean.Spec.M.API_Types.messageInfoFromWord 2)}"
#eval IO.println s!"73|{showS (Sel4Lean.Spec.M.API_Types.wordFromMessageInfo (_root_.Sel4Lean.Spec.MessageInfo.MI 1 6781704140997882399 1 1))}"
#eval IO.println s!"74|{showS (Sel4Lean.Spec.M.API_Types.wordFromMessageInfo (_root_.Sel4Lean.Spec.MessageInfo.MI 3743209414099974862 18446744073709551615 15118712896221991143 7))}"
#eval IO.println s!"75|{showS (Sel4Lean.Spec.M.API_Types.wordFromMessageInfo (_root_.Sel4Lean.Spec.MessageInfo.MI 1 9223372036854775808 7 1))}"
#eval IO.println s!"76|{showS (Sel4Lean.Spec.M.API_Types.wordFromMessageInfo (_root_.Sel4Lean.Spec.MessageInfo.MI 9223372036854775808 0 7 9223372036854775808))}"
#eval IO.println s!"77|{showS (Sel4Lean.Spec.M.API_Types.wordFromMessageInfo (_root_.Sel4Lean.Spec.MessageInfo.MI 4226431011039801856 1 2 1))}"
#eval IO.println s!"78|{showS (Sel4Lean.Spec.M.API_Types.wordFromMessageInfo (_root_.Sel4Lean.Spec.MessageInfo.MI 18446744073709551615 2 9223372036854775808 1))}"
#eval IO.println s!"79|{showS (Sel4Lean.Spec.M.API_Types.ptrFromPAddrRegion ((_root_.Sel4Lean.Spec.PAddr.PAddr 0), (_root_.Sel4Lean.Spec.PAddr.PAddr 2)))}"
#eval IO.println s!"80|{showS (Sel4Lean.Spec.M.API_Types.ptrFromPAddrRegion ((_root_.Sel4Lean.Spec.PAddr.PAddr 9223372036854775808), (_root_.Sel4Lean.Spec.PAddr.PAddr 0)))}"
#eval IO.println s!"81|{showS (Sel4Lean.Spec.M.API_Types.ptrFromPAddrRegion ((_root_.Sel4Lean.Spec.PAddr.PAddr 18446744073709551615), (_root_.Sel4Lean.Spec.PAddr.PAddr 0)))}"
#eval IO.println s!"82|{showS (Sel4Lean.Spec.M.API_Types.ptrFromPAddrRegion ((_root_.Sel4Lean.Spec.PAddr.PAddr 1), (_root_.Sel4Lean.Spec.PAddr.PAddr 18446744073709551615)))}"
#eval IO.println s!"83|{showS (Sel4Lean.Spec.M.API_Types.ptrFromPAddrRegion ((_root_.Sel4Lean.Spec.PAddr.PAddr 18446744073709551615), (_root_.Sel4Lean.Spec.PAddr.PAddr 1)))}"
#eval IO.println s!"84|{showS (Sel4Lean.Spec.M.API_Types.ptrFromPAddrRegion ((_root_.Sel4Lean.Spec.PAddr.PAddr 0), (_root_.Sel4Lean.Spec.PAddr.PAddr 8860385287354296225)))}"
#eval IO.println s!"85|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.EndpointObject))}"
#eval IO.println s!"86|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.TCBObject))}"
#eval IO.println s!"87|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.Untyped))}"
#eval IO.println s!"88|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.EndpointObject))}"
#eval IO.println s!"89|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.Untyped))}"
#eval IO.println s!"90|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.fromAPIType (_root_.Sel4Lean.Spec.APIObjectType.TCBObject))}"
#eval IO.println s!"91|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.toAPIType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"92|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.toAPIType (_root_.Sel4Lean.Spec.ObjectType.LargePageObject))}"
#eval IO.println s!"93|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.toAPIType (_root_.Sel4Lean.Spec.ObjectType.HugePageObject))}"
#eval IO.println s!"94|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.toAPIType (_root_.Sel4Lean.Spec.ObjectType.LargePageObject))}"
#eval IO.println s!"95|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.toAPIType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"96|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.toAPIType (_root_.Sel4Lean.Spec.ObjectType.HugePageObject))}"
#eval IO.println s!"97|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.apiGetObjectSize (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject) 3)}"
#eval IO.println s!"98|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.apiGetObjectSize (_root_.Sel4Lean.Spec.APIObjectType.EndpointObject) 5)}"
#eval IO.println s!"99|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.apiGetObjectSize (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject) 63)}"
#eval IO.println s!"100|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.apiGetObjectSize (_root_.Sel4Lean.Spec.APIObjectType.TCBObject) 3)}"
#eval IO.println s!"101|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.apiGetObjectSize (_root_.Sel4Lean.Spec.APIObjectType.CapTableObject) 8)}"
#eval IO.println s!"102|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.apiGetObjectSize (_root_.Sel4Lean.Spec.APIObjectType.NotificationObject) 0)}"
#eval IO.println s!"103|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.PageTableObject) 63)}"
#eval IO.println s!"104|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject) 12)}"
#eval IO.println s!"105|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.HugePageObject) 8)}"
#eval IO.println s!"106|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.LargePageObject) 0)}"
#eval IO.println s!"107|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.APIObjectType (_root_.Sel4Lean.Spec.APIObjectType.EndpointObject)) 0)}"
#eval IO.println s!"108|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.getObjectSize (_root_.Sel4Lean.Spec.ObjectType.LargePageObject) 12)}"
#eval IO.println s!"109|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.isFrameType (_root_.Sel4Lean.Spec.ObjectType.HugePageObject))}"
#eval IO.println s!"110|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.isFrameType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"111|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.isFrameType (_root_.Sel4Lean.Spec.ObjectType.LargePageObject))}"
#eval IO.println s!"112|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.isFrameType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"113|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.isFrameType (_root_.Sel4Lean.Spec.ObjectType.LargePageObject))}"
#eval IO.println s!"114|{showS (Sel4Lean.Spec.M.API_Types_RISCV64.isFrameType (_root_.Sel4Lean.Spec.ObjectType.SmallPageObject))}"
#eval IO.println s!"115|{showS (Sel4Lean.Spec.M.Kernel_Thread.invertL1Index 31)}"
#eval IO.println s!"116|{showS (Sel4Lean.Spec.M.Kernel_Thread.invertL1Index 31)}"
#eval IO.println s!"117|{showS (Sel4Lean.Spec.M.Kernel_Thread.invertL1Index 5)}"
#eval IO.println s!"118|{showS (Sel4Lean.Spec.M.Kernel_Thread.invertL1Index 12)}"
#eval IO.println s!"119|{showS (Sel4Lean.Spec.M.Kernel_Thread.invertL1Index 8)}"
#eval IO.println s!"120|{showS (Sel4Lean.Spec.M.Kernel_Thread.invertL1Index 2)}"
#eval IO.println s!"121|{showS (Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index 255)}"
#eval IO.println s!"122|{showS (Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index 1)}"
#eval IO.println s!"123|{showS (Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index 2)}"
#eval IO.println s!"124|{showS (Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index 7)}"
#eval IO.println s!"125|{showS (Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index 2)}"
#eval IO.println s!"126|{showS (Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index 128)}"
#eval IO.println s!"127|{showS (Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio 0)}"
#eval IO.println s!"128|{showS (Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio 1)}"
#eval IO.println s!"129|{showS (Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio 12)}"
#eval IO.println s!"130|{showS (Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio 31)}"
#eval IO.println s!"131|{showS (Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio 0)}"
#eval IO.println s!"132|{showS (Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio 8)}"
#eval IO.println s!"133|{showS (Sel4Lean.Spec.M.Kernel_VSpace.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨4096⟩))}"
#eval IO.println s!"134|{showS (Sel4Lean.Spec.M.Kernel_VSpace.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨18446743798831648768⟩ 8396814629979256605 true true true true))}"
#eval IO.println s!"135|{showS (Sel4Lean.Spec.M.Kernel_VSpace.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨4096⟩ false false))}"
#eval IO.println s!"136|{showS (Sel4Lean.Spec.M.Kernel_VSpace.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨11357795504435716725⟩ 7 true false))}"
#eval IO.println s!"137|{showS (Sel4Lean.Spec.M.Kernel_VSpace.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.DomainCap))}"
#eval IO.println s!"138|{showS (Sel4Lean.Spec.M.Kernel_VSpace.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.NullCap))}"
#eval IO.println s!"139|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft 63)}"
#eval IO.println s!"140|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft 12)}"
#eval IO.println s!"141|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft 1)}"
#eval IO.println s!"142|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft 12)}"
#eval IO.println s!"143|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft 5)}"
#eval IO.println s!"144|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft 8)}"
#eval IO.println s!"145|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex 12 (_root_.Sel4Lean.Spec.VPtr.VPtr 9223372036854775808))}"
#eval IO.println s!"146|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex 1 (_root_.Sel4Lean.Spec.VPtr.VPtr 7))}"
#eval IO.println s!"147|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex 8 (_root_.Sel4Lean.Spec.VPtr.VPtr 1))}"
#eval IO.println s!"148|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex 12 (_root_.Sel4Lean.Spec.VPtr.VPtr 0))}"
#eval IO.println s!"149|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex 3 (_root_.Sel4Lean.Spec.VPtr.VPtr 18446744073709551615))}"
#eval IO.println s!"150|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex 8 (_root_.Sel4Lean.Spec.VPtr.VPtr 8755164007601772092))}"
#eval IO.println s!"151|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex 2 ⟨0⟩ (_root_.Sel4Lean.Spec.VPtr.VPtr 7))}"
#eval IO.println s!"152|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex 0 ⟨4096⟩ (_root_.Sel4Lean.Spec.VPtr.VPtr 1))}"
#eval IO.println s!"153|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex 2 ⟨7953063811814215960⟩ (_root_.Sel4Lean.Spec.VPtr.VPtr 1))}"
#eval IO.println s!"154|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex 5 ⟨6966882839995559656⟩ (_root_.Sel4Lean.Spec.VPtr.VPtr 1))}"
#eval IO.println s!"155|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex 3 ⟨0⟩ (_root_.Sel4Lean.Spec.VPtr.VPtr 11457940526213730888))}"
#eval IO.println s!"156|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex 63 ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VPtr.VPtr 1))}"
#eval IO.println s!"157|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 31) 12))}"
#eval IO.println s!"158|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨4096⟩ 15531181880376575917 false true))}"
#eval IO.println s!"159|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨4096⟩ 8 7 0))}"
#eval IO.println s!"160|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 8))}"
#eval IO.println s!"161|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨0⟩ 7 true true))}"
#eval IO.println s!"162|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.isValidVTableRoot (_root_.Sel4Lean.Spec.Capability.UntypedCap true ⟨3719802708160397093⟩ 63 63))}"
#eval IO.println s!"163|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.maskVMRights (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.CapRights.CapRights false false true false))}"
#eval IO.println s!"164|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.maskVMRights (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.CapRights.CapRights true false true false))}"
#eval IO.println s!"165|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.maskVMRights (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.CapRights.CapRights false true true false))}"
#eval IO.println s!"166|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.maskVMRights (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.CapRights.CapRights false false true true))}"
#eval IO.println s!"167|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.maskVMRights (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.CapRights.CapRights true false true true))}"
#eval IO.println s!"168|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.maskVMRights (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.CapRights.CapRights false true false false))}"
#eval IO.println s!"169|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.attribsFromWord 17884116492589374499)}"
#eval IO.println s!"170|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.attribsFromWord 18446744073709551615)}"
#eval IO.println s!"171|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.attribsFromWord 9223372036854775808)}"
#eval IO.println s!"172|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.attribsFromWord 9223372036854775808)}"
#eval IO.println s!"173|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.attribsFromWord 18446744073709551615)}"
#eval IO.println s!"174|{showS (Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.attribsFromWord 9223372036854775808)}"
#eval IO.println s!"175|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmFaultTypeFSR (_root_.Sel4Lean.Spec.VMFaultType.RISCVInstructionPageFault))}"
#eval IO.println s!"176|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmFaultTypeFSR (_root_.Sel4Lean.Spec.VMFaultType.RISCVStoreAccessFault))}"
#eval IO.println s!"177|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmFaultTypeFSR (_root_.Sel4Lean.Spec.VMFaultType.RISCVLoadPageFault))}"
#eval IO.println s!"178|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmFaultTypeFSR (_root_.Sel4Lean.Spec.VMFaultType.RISCVInstructionPageFault))}"
#eval IO.println s!"179|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmFaultTypeFSR (_root_.Sel4Lean.Spec.VMFaultType.RISCVStorePageFault))}"
#eval IO.println s!"180|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmFaultTypeFSR (_root_.Sel4Lean.Spec.VMFaultType.RISCVStoreAccessFault))}"
#eval IO.println s!"181|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (_root_.Sel4Lean.Spec.PAddr.PAddr 5570928653271953894))}"
#eval IO.println s!"182|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (_root_.Sel4Lean.Spec.PAddr.PAddr 2))}"
#eval IO.println s!"183|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (_root_.Sel4Lean.Spec.PAddr.PAddr 18446744073709551615))}"
#eval IO.println s!"184|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (_root_.Sel4Lean.Spec.PAddr.PAddr 9223372036854775808))}"
#eval IO.println s!"185|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (_root_.Sel4Lean.Spec.PAddr.PAddr 7))}"
#eval IO.println s!"186|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (_root_.Sel4Lean.Spec.PAddr.PAddr 1))}"
#eval IO.println s!"187|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBitsForSize (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage))}"
#eval IO.println s!"188|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBitsForSize (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage))}"
#eval IO.println s!"189|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBitsForSize (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage))}"
#eval IO.println s!"190|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBitsForSize (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage))}"
#eval IO.println s!"191|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBitsForSize (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage))}"
#eval IO.println s!"192|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBitsForSize (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage))}"
#eval IO.println s!"193|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsToBits (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"194|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsToBits (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"195|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsToBits (_root_.Sel4Lean.Spec.VMRights.VMReadOnly))}"
#eval IO.println s!"196|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsToBits (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"197|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsToBits (_root_.Sel4Lean.Spec.VMRights.VMReadWrite))}"
#eval IO.println s!"198|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsToBits (_root_.Sel4Lean.Spec.VMRights.VMReadWrite))}"
#eval IO.println s!"199|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowWrite (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"200|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowWrite (_root_.Sel4Lean.Spec.VMRights.VMReadWrite))}"
#eval IO.println s!"201|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowWrite (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"202|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowWrite (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"203|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowWrite (_root_.Sel4Lean.Spec.VMRights.VMReadOnly))}"
#eval IO.println s!"204|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowWrite (_root_.Sel4Lean.Spec.VMRights.VMReadOnly))}"
#eval IO.println s!"205|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowRead (_root_.Sel4Lean.Spec.VMRights.VMReadOnly))}"
#eval IO.println s!"206|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowRead (_root_.Sel4Lean.Spec.VMRights.VMReadOnly))}"
#eval IO.println s!"207|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowRead (_root_.Sel4Lean.Spec.VMRights.VMReadWrite))}"
#eval IO.println s!"208|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowRead (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"209|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowRead (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly))}"
#eval IO.println s!"210|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.allowRead (_root_.Sel4Lean.Spec.VMRights.VMReadOnly))}"
#eval IO.println s!"211|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.getVMRights false false)}"
#eval IO.println s!"212|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.getVMRights false false)}"
#eval IO.println s!"213|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.getVMRights false false)}"
#eval IO.println s!"214|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.getVMRights false false)}"
#eval IO.println s!"215|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.getVMRights true true)}"
#eval IO.println s!"216|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.getVMRights false false)}"
#eval IO.println s!"217|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsFromBits 9223372036854775808)}"
#eval IO.println s!"218|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsFromBits 13762821540780960100)}"
#eval IO.println s!"219|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsFromBits 2)}"
#eval IO.println s!"220|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsFromBits 9223372036854775808)}"
#eval IO.println s!"221|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsFromBits 7)}"
#eval IO.println s!"222|{showS (Sel4Lean.Spec.M.Machine_Hardware_RISCV64.vmRightsFromBits 18259339806008887473)}"
#eval IO.println s!"223|{showS (Sel4Lean.Spec.M.Object_CNode.capCyclicZombie (_root_.Sel4Lean.Spec.Capability.IRQControlCap) ⟨9253663193712232411⟩)}"
#eval IO.println s!"224|{showS (Sel4Lean.Spec.M.Object_CNode.capCyclicZombie (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨0⟩ 8 1 0) ⟨4096⟩)}"
#eval IO.println s!"225|{showS (Sel4Lean.Spec.M.Object_CNode.capCyclicZombie (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨5529717657452303722⟩) ⟨0⟩)}"
#eval IO.println s!"226|{showS (Sel4Lean.Spec.M.Object_CNode.capCyclicZombie (_root_.Sel4Lean.Spec.Capability.UntypedCap true ⟨18446743798831648768⟩ 3 5) ⟨18446743798831648768⟩)}"
#eval IO.println s!"227|{showS (Sel4Lean.Spec.M.Object_CNode.capCyclicZombie (_root_.Sel4Lean.Spec.Capability.Zombie ⟨0⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 3) 31) ⟨18446743798831648768⟩)}"
#eval IO.println s!"228|{showS (Sel4Lean.Spec.M.Object_CNode.capCyclicZombie (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨4096⟩ 5 4910089519752444777 1) ⟨2799954844560634387⟩)}"
#eval IO.println s!"229|{showS (Sel4Lean.Spec.M.Object_CNode.capRemovable (_root_.Sel4Lean.Spec.Capability.DomainCap) ⟨10009772024557087486⟩)}"
#eval IO.println s!"230|{showS (Sel4Lean.Spec.M.Object_CNode.capRemovable (_root_.Sel4Lean.Spec.Capability.NullCap) ⟨18446743798831648768⟩)}"
#eval IO.println s!"231|{showS (Sel4Lean.Spec.M.Object_CNode.capRemovable (_root_.Sel4Lean.Spec.Capability.UntypedCap true ⟨13642697554756203947⟩ 31 1) ⟨3549837695822867536⟩)}"
#eval IO.println s!"232|{showS (Sel4Lean.Spec.M.Object_CNode.capRemovable (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨0⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage) false none)) ⟨8746577854599144557⟩)}"
#eval IO.println s!"233|{showS (Sel4Lean.Spec.M.Object_CNode.capRemovable (_root_.Sel4Lean.Spec.Capability.IRQControlCap) ⟨0⟩)}"
#eval IO.println s!"234|{showS (Sel4Lean.Spec.M.Object_CNode.capRemovable (_root_.Sel4Lean.Spec.Capability.UntypedCap false ⟨4096⟩ 5 5) ⟨4180529646233636398⟩)}"
#eval IO.println s!"235|{showS (Sel4Lean.Spec.M.Object_CNode.longRunningDelete (_root_.Sel4Lean.Spec.Capability.DomainCap))}"
#eval IO.println s!"236|{showS (Sel4Lean.Spec.M.Object_CNode.longRunningDelete (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨18446743798831648768⟩ 16866007481423189284 false false false false))}"
#eval IO.println s!"237|{showS (Sel4Lean.Spec.M.Object_CNode.longRunningDelete (_root_.Sel4Lean.Spec.Capability.IRQHandlerCap (_root_.Sel4Lean.Spec.IRQ.IRQ (_root_.Sel4Lean.Spec.RISCV64.IRQ.IRQ 2))))}"
#eval IO.println s!"238|{showS (Sel4Lean.Spec.M.Object_CNode.longRunningDelete (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨6653419665099924296⟩ 12 2 5))}"
#eval IO.println s!"239|{showS (Sel4Lean.Spec.M.Object_CNode.longRunningDelete (_root_.Sel4Lean.Spec.Capability.IRQControlCap))}"
#eval IO.println s!"240|{showS (Sel4Lean.Spec.M.Object_CNode.longRunningDelete (_root_.Sel4Lean.Spec.Capability.DomainCap))}"
#eval IO.println s!"241|{showS (Sel4Lean.Spec.M.Object_Endpoint.isActive (_root_.Sel4Lean.Spec.Notification.NTFN (_root_.Sel4Lean.Spec.NTFN.IdleNtfn) none))}"
#eval IO.println s!"242|{showS (Sel4Lean.Spec.M.Object_Endpoint.isActive (_root_.Sel4Lean.Spec.Notification.NTFN (_root_.Sel4Lean.Spec.NTFN.IdleNtfn) (some ⟨18100126880938075189⟩)))}"
#eval IO.println s!"243|{showS (Sel4Lean.Spec.M.Object_Endpoint.isActive (_root_.Sel4Lean.Spec.Notification.NTFN (_root_.Sel4Lean.Spec.NTFN.WaitingNtfn []) (some ⟨0⟩)))}"
#eval IO.println s!"244|{showS (Sel4Lean.Spec.M.Object_Endpoint.isActive (_root_.Sel4Lean.Spec.Notification.NTFN (_root_.Sel4Lean.Spec.NTFN.ActiveNtfn 1) none))}"
#eval IO.println s!"245|{showS (Sel4Lean.Spec.M.Object_Endpoint.isActive (_root_.Sel4Lean.Spec.Notification.NTFN (_root_.Sel4Lean.Spec.NTFN.IdleNtfn) none))}"
#eval IO.println s!"246|{showS (Sel4Lean.Spec.M.Object_Endpoint.isActive (_root_.Sel4Lean.Spec.Notification.NTFN (_root_.Sel4Lean.Spec.NTFN.IdleNtfn) none))}"
#eval IO.println s!"247|{showS (Sel4Lean.Spec.M.Object_Interrupt.toBool 7)}"
#eval IO.println s!"248|{showS (Sel4Lean.Spec.M.Object_Interrupt.toBool 7434553032980896337)}"
#eval IO.println s!"249|{showS (Sel4Lean.Spec.M.Object_Interrupt.toBool 7)}"
#eval IO.println s!"250|{showS (Sel4Lean.Spec.M.Object_Interrupt.toBool 7)}"
#eval IO.println s!"251|{showS (Sel4Lean.Spec.M.Object_Interrupt.toBool 0)}"
#eval IO.println s!"252|{showS (Sel4Lean.Spec.M.Object_Interrupt.toBool 9223372036854775808)}"
#eval IO.println s!"253|{showS (Sel4Lean.Spec.M.Object_Notification.receiveBlocked (_root_.Sel4Lean.Spec.ThreadState.Inactive))}"
#eval IO.println s!"254|{showS (Sel4Lean.Spec.M.Object_Notification.receiveBlocked (_root_.Sel4Lean.Spec.ThreadState.BlockedOnReceive ⟨17702841481314720039⟩ false))}"
#eval IO.println s!"255|{showS (Sel4Lean.Spec.M.Object_Notification.receiveBlocked (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"256|{showS (Sel4Lean.Spec.M.Object_Notification.receiveBlocked (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"257|{showS (Sel4Lean.Spec.M.Object_Notification.receiveBlocked (_root_.Sel4Lean.Spec.ThreadState.Inactive))}"
#eval IO.println s!"258|{showS (Sel4Lean.Spec.M.Object_Notification.receiveBlocked (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"259|{showS (Sel4Lean.Spec.M.Object_ObjectType.isCapRevocable (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨4096⟩ 0 18446744073709551615 31) (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨0⟩ 18446744073709551615 true false))}"
#eval IO.println s!"260|{showS (Sel4Lean.Spec.M.Object_ObjectType.isCapRevocable (_root_.Sel4Lean.Spec.Capability.NullCap) (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨12314481742158297701⟩ 31 18446744073709551615 31))}"
#eval IO.println s!"261|{showS (Sel4Lean.Spec.M.Object_ObjectType.isCapRevocable (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨18446743798831648768⟩ 0 false false true false) (_root_.Sel4Lean.Spec.Capability.IRQControlCap))}"
#eval IO.println s!"262|{showS (Sel4Lean.Spec.M.Object_ObjectType.isCapRevocable (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨4096⟩ true true) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 1774021578358400095))))}"
#eval IO.println s!"263|{showS (Sel4Lean.Spec.M.Object_ObjectType.isCapRevocable (_root_.Sel4Lean.Spec.Capability.NullCap) (_root_.Sel4Lean.Spec.Capability.DomainCap))}"
#eval IO.println s!"264|{showS (Sel4Lean.Spec.M.Object_ObjectType.isCapRevocable (_root_.Sel4Lean.Spec.Capability.Zombie ⟨0⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 8) 0) (_root_.Sel4Lean.Spec.Capability.Zombie ⟨4096⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 63))}"
#eval IO.println s!"265|{showS (Sel4Lean.Spec.M.Object_ObjectType.hasCancelSendRights (_root_.Sel4Lean.Spec.Capability.IRQHandlerCap (_root_.Sel4Lean.Spec.IRQ.IRQ (_root_.Sel4Lean.Spec.RISCV64.IRQ.IRQ 4294967295))))}"
#eval IO.println s!"266|{showS (Sel4Lean.Spec.M.Object_ObjectType.hasCancelSendRights (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨15960127133837414590⟩ 0 false true))}"
#eval IO.println s!"267|{showS (Sel4Lean.Spec.M.Object_ObjectType.hasCancelSendRights (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 0), (_root_.Sel4Lean.Spec.VPtr.VPtr 1))))))}"
#eval IO.println s!"268|{showS (Sel4Lean.Spec.M.Object_ObjectType.hasCancelSendRights (_root_.Sel4Lean.Spec.Capability.Zombie ⟨0⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 0) 31))}"
#eval IO.println s!"269|{showS (Sel4Lean.Spec.M.Object_ObjectType.hasCancelSendRights (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨18446743798831648768⟩ 4292225269526381843 false false false false))}"
#eval IO.println s!"270|{showS (Sel4Lean.Spec.M.Object_ObjectType.hasCancelSendRights (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨4096⟩))}"
#eval IO.println s!"271|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedPtr (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨5803039517496103198⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage) true none)))}"
#eval IO.println s!"272|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedPtr (_root_.Sel4Lean.Spec.Capability.NullCap))}"
#eval IO.println s!"273|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedPtr (_root_.Sel4Lean.Spec.Capability.NullCap))}"
#eval IO.println s!"274|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedPtr (_root_.Sel4Lean.Spec.Capability.UntypedCap true ⟨4096⟩ 0 31))}"
#eval IO.println s!"275|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedPtr (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨4096⟩ 1 false false))}"
#eval IO.println s!"276|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedPtr (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨18446743798831648768⟩ 9223372036854775808 true true false true))}"
#eval IO.println s!"277|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedSize (_root_.Sel4Lean.Spec.Capability.UntypedCap false ⟨5272515988908798385⟩ 8 1))}"
#eval IO.println s!"278|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedSize (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 3) 1))}"
#eval IO.println s!"279|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedSize (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 1))))}"
#eval IO.println s!"280|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedSize (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨10758763135545366522⟩ 6226125199538744559 false false false false))}"
#eval IO.println s!"281|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedSize (_root_.Sel4Lean.Spec.Capability.NullCap))}"
#eval IO.println s!"282|{showS (Sel4Lean.Spec.M.Object_ObjectType.capUntypedSize (_root_.Sel4Lean.Spec.Capability.IRQHandlerCap (_root_.Sel4Lean.Spec.IRQ.IRQ (_root_.Sel4Lean.Spec.RISCV64.IRQ.IRQ 7))))}"
#eval IO.println s!"283|{showS (Sel4Lean.Spec.M.Object_ObjectType.isPhysicalCap (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨674170234479172706⟩ 2 false true true false))}"
#eval IO.println s!"284|{showS (Sel4Lean.Spec.M.Object_ObjectType.isPhysicalCap (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨0⟩ 8 0 2))}"
#eval IO.println s!"285|{showS (Sel4Lean.Spec.M.Object_ObjectType.isPhysicalCap (_root_.Sel4Lean.Spec.Capability.Zombie ⟨16456272235773647469⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 3))}"
#eval IO.println s!"286|{showS (Sel4Lean.Spec.M.Object_ObjectType.isPhysicalCap (_root_.Sel4Lean.Spec.Capability.IRQHandlerCap (_root_.Sel4Lean.Spec.IRQ.IRQ (_root_.Sel4Lean.Spec.RISCV64.IRQ.IRQ 2))))}"
#eval IO.println s!"287|{showS (Sel4Lean.Spec.M.Object_ObjectType.isPhysicalCap (_root_.Sel4Lean.Spec.Capability.Zombie ⟨4096⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 63))}"
#eval IO.println s!"288|{showS (Sel4Lean.Spec.M.Object_ObjectType.isPhysicalCap (_root_.Sel4Lean.Spec.Capability.Zombie ⟨4096⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 5) 8))}"
#eval IO.println s!"289|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameRegionAs (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨0⟩ 8 7 8) (_root_.Sel4Lean.Spec.Capability.IRQControlCap))}"
#eval IO.println s!"290|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameRegionAs (_root_.Sel4Lean.Spec.Capability.UntypedCap false ⟨18446743798831648768⟩ 12 31) (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨4096⟩ false true))}"
#eval IO.println s!"291|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameRegionAs (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 0))) (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨0⟩ true false))}"
#eval IO.println s!"292|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameRegionAs (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨3368054375605415858⟩ 3 9223372036854775808 1) (_root_.Sel4Lean.Spec.Capability.NullCap))}"
#eval IO.println s!"293|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameRegionAs (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨18095684930460554657⟩ 18446744073709551615 false false) (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨4096⟩ 63 18446744073709551615 31))}"
#eval IO.println s!"294|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameRegionAs (_root_.Sel4Lean.Spec.Capability.DomainCap) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ASID.ASID 1))))}"
#eval IO.println s!"295|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameObjectAs (_root_.Sel4Lean.Spec.Capability.IRQControlCap) (_root_.Sel4Lean.Spec.Capability.UntypedCap false ⟨11206214349964642812⟩ 31 63))}"
#eval IO.println s!"296|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameObjectAs (_root_.Sel4Lean.Spec.Capability.NullCap) (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨4096⟩ 1331826267399059396 false false))}"
#eval IO.println s!"297|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameObjectAs (_root_.Sel4Lean.Spec.Capability.NullCap) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) false none)))}"
#eval IO.println s!"298|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameObjectAs (_root_.Sel4Lean.Spec.Capability.Zombie ⟨4096⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 12) (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨12311407029756315022⟩ false false))}"
#eval IO.println s!"299|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameObjectAs (_root_.Sel4Lean.Spec.Capability.DomainCap) (_root_.Sel4Lean.Spec.Capability.IRQHandlerCap (_root_.Sel4Lean.Spec.IRQ.IRQ (_root_.Sel4Lean.Spec.RISCV64.IRQ.IRQ 4294967295))))}"
#eval IO.println s!"300|{showS (Sel4Lean.Spec.M.Object_ObjectType.sameObjectAs (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨2314351069356255645⟩) (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨0⟩))}"
#eval IO.println s!"301|{showS (Sel4Lean.Spec.M.Object_ObjectType.updateCapData false 2 (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 2))))}"
#eval IO.println s!"302|{showS (Sel4Lean.Spec.M.Object_ObjectType.updateCapData false 18446744073709551615 (_root_.Sel4Lean.Spec.Capability.IRQControlCap))}"
#eval IO.println s!"303|{showS (Sel4Lean.Spec.M.Object_ObjectType.updateCapData true 18446744073709551615 (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨18446743798831648768⟩))}"
#eval IO.println s!"304|{showS (Sel4Lean.Spec.M.Object_ObjectType.updateCapData false 2 (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨0⟩ 1 false false))}"
#eval IO.println s!"305|{showS (Sel4Lean.Spec.M.Object_ObjectType.updateCapData true 1 (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨18446743798831648768⟩ 6615156368457400243 false true))}"
#eval IO.println s!"306|{showS (Sel4Lean.Spec.M.Object_ObjectType.updateCapData true 18446744073709551615 (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨18446743798831648768⟩ false true))}"
#eval IO.println s!"307|{showS (Sel4Lean.Spec.M.Object_ObjectType.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true false true) (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨9260937092048439444⟩ 2 true true))}"
#eval IO.println s!"308|{showS (Sel4Lean.Spec.M.Object_ObjectType.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false false true false) (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 1))}"
#eval IO.println s!"309|{showS (Sel4Lean.Spec.M.Object_ObjectType.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true true false) (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨18446743798831648768⟩))}"
#eval IO.println s!"310|{showS (Sel4Lean.Spec.M.Object_ObjectType.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true true false) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨0⟩ (some ((_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808), (_root_.Sel4Lean.Spec.VPtr.VPtr 9223372036854775808))))))}"
#eval IO.println s!"311|{showS (Sel4Lean.Spec.M.Object_ObjectType.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true false true) (_root_.Sel4Lean.Spec.Capability.DomainCap))}"
#eval IO.println s!"312|{showS (Sel4Lean.Spec.M.Object_ObjectType.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true false true) (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 1) 0))}"
#eval IO.println s!"313|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isCapRevocable (_root_.Sel4Lean.Spec.Capability.ThreadCap ⟨18446743798831648768⟩) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨14603666833089023447⟩ (_root_.Sel4Lean.Spec.ASID.ASID 7))))}"
#eval IO.println s!"314|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isCapRevocable (_root_.Sel4Lean.Spec.Capability.DomainCap) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨10104187088853114028⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) true none)))}"
#eval IO.println s!"315|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isCapRevocable (_root_.Sel4Lean.Spec.Capability.IRQControlCap) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨0⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage) false none)))}"
#eval IO.println s!"316|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isCapRevocable (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨16770122413532581806⟩ none)) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap)))}"
#eval IO.println s!"317|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isCapRevocable (_root_.Sel4Lean.Spec.Capability.DomainCap) (_root_.Sel4Lean.Spec.Capability.NullCap))}"
#eval IO.println s!"318|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isCapRevocable (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 0) (_root_.Sel4Lean.Spec.Capability.IRQControlCap))}"
#eval IO.println s!"319|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isArchMDBParentOf (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨0⟩ true false) (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨14744537165980786331⟩ false true) false)}"
#eval IO.println s!"320|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isArchMDBParentOf (_root_.Sel4Lean.Spec.Capability.NullCap) (_root_.Sel4Lean.Spec.Capability.NullCap) true)}"
#eval IO.println s!"321|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isArchMDBParentOf (_root_.Sel4Lean.Spec.Capability.EndpointCap ⟨5614251237087299510⟩ 18446744073709551615 true false false true) (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨18446743798831648768⟩ false false) true)}"
#eval IO.println s!"322|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isArchMDBParentOf (_root_.Sel4Lean.Spec.Capability.IRQHandlerCap (_root_.Sel4Lean.Spec.IRQ.IRQ (_root_.Sel4Lean.Spec.RISCV64.IRQ.IRQ 4294967295))) (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap)) true)}"
#eval IO.println s!"323|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isArchMDBParentOf (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨17854380445249498745⟩ 0 7 5) (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨4096⟩ 1 9223372036854775808 8) true)}"
#eval IO.println s!"324|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isArchMDBParentOf (_root_.Sel4Lean.Spec.Capability.UntypedCap false ⟨4096⟩ 3 2) (_root_.Sel4Lean.Spec.Capability.ReplyCap ⟨0⟩ false false) false)}"
#eval IO.println s!"325|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.updateCapData false 8677653900933427632 (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"326|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.updateCapData false 18446744073709551615 (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨2022458009075254955⟩ (_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808)))}"
#eval IO.println s!"327|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.updateCapData true 9223372036854775808 (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 0), (_root_.Sel4Lean.Spec.VPtr.VPtr 9223372036854775808)))))}"
#eval IO.println s!"328|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.updateCapData true 9223372036854775808 (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808)))}"
#eval IO.println s!"329|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.updateCapData true 18446744073709551615 (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨14758656996101253483⟩ (_root_.Sel4Lean.Spec.ASID.ASID 7516976170253644239)))}"
#eval IO.println s!"330|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.updateCapData true 4364191165752916711 (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) true none))}"
#eval IO.println s!"331|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true false false true) (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨15995141418096361895⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage) false none))}"
#eval IO.println s!"332|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true false false true) (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ASID.ASID 10292304265859115967)))}"
#eval IO.println s!"333|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true true true) (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) true none))}"
#eval IO.println s!"334|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false true true false) (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 1)))}"
#eval IO.println s!"335|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights false false true false) (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ASID.ASID 0)))}"
#eval IO.println s!"336|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.maskCapRights (_root_.Sel4Lean.Spec.CapRights.CapRights true true false false) (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"337|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isIRQControlCapDescendant (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 18446744073709551615)))}"
#eval IO.println s!"338|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isIRQControlCapDescendant (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨18446743798831648768⟩ none))}"
#eval IO.println s!"339|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isIRQControlCapDescendant (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨0⟩ (some ((_root_.Sel4Lean.Spec.ASID.ASID 7), (_root_.Sel4Lean.Spec.VPtr.VPtr 2)))))}"
#eval IO.println s!"340|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isIRQControlCapDescendant (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨7345111759890236607⟩ (_root_.Sel4Lean.Spec.ASID.ASID 2)))}"
#eval IO.println s!"341|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isIRQControlCapDescendant (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨18446743798831648768⟩ none))}"
#eval IO.println s!"342|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isIRQControlCapDescendant (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨1341923828123645398⟩ none))}"
#eval IO.println s!"343|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameRegionAs (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨2913447850300151621⟩ none) (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) true (some ((_root_.Sel4Lean.Spec.ASID.ASID 0), (_root_.Sel4Lean.Spec.VPtr.VPtr 18446744073709551615)))))}"
#eval IO.println s!"344|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameRegionAs (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 1), (_root_.Sel4Lean.Spec.VPtr.VPtr 2)))) (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"345|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameRegionAs (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨0⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 1), (_root_.Sel4Lean.Spec.VPtr.VPtr 18446744073709551615)))) (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 2)))}"
#eval IO.println s!"346|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameRegionAs (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap) (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨15113486313327519409⟩ none))}"
#eval IO.println s!"347|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameRegionAs (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨15030486100016450666⟩ (some ((_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808), (_root_.Sel4Lean.Spec.VPtr.VPtr 9223372036854775808)))) (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"348|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameRegionAs (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 7), (_root_.Sel4Lean.Spec.VPtr.VPtr 2)))) (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨0⟩ none))}"
#eval IO.println s!"349|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isPhysicalCap (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨15848316641091461264⟩ none))}"
#eval IO.println s!"350|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isPhysicalCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 7)))}"
#eval IO.println s!"351|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isPhysicalCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808)))}"
#eval IO.println s!"352|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isPhysicalCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 0)))}"
#eval IO.println s!"353|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isPhysicalCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨15520455319821403804⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) false none))}"
#eval IO.println s!"354|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.isPhysicalCap (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) true (some ((_root_.Sel4Lean.Spec.ASID.ASID 0), (_root_.Sel4Lean.Spec.VPtr.VPtr 2)))))}"
#eval IO.println s!"355|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameObjectAs (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap) (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) true none))}"
#eval IO.println s!"356|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameObjectAs (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨0⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) false none) (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"357|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameObjectAs (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) true none) (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 2)))}"
#eval IO.println s!"358|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameObjectAs (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 7)) (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 18446744073709551615), (_root_.Sel4Lean.Spec.VPtr.VPtr 9223372036854775808)))))}"
#eval IO.println s!"359|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameObjectAs (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap) (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨18446743798831648768⟩ (some ((_root_.Sel4Lean.Spec.ASID.ASID 2), (_root_.Sel4Lean.Spec.VPtr.VPtr 18446744073709551615)))))}"
#eval IO.println s!"360|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.sameObjectAs (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap) (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"361|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedPtr (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 7)))}"
#eval IO.println s!"362|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedPtr (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"363|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedPtr (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap))}"
#eval IO.println s!"364|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedPtr (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) true (some ((_root_.Sel4Lean.Spec.ASID.ASID 0), (_root_.Sel4Lean.Spec.VPtr.VPtr 2)))))}"
#eval IO.println s!"365|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedPtr (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨0⟩ (_root_.Sel4Lean.Spec.ASID.ASID 7)))}"
#eval IO.println s!"366|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedPtr (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMKernelOnly) (_root_.Sel4Lean.Spec.VMPageSize.RISCVHugePage) true none))}"
#eval IO.println s!"367|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedSize (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808)))}"
#eval IO.println s!"368|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedSize (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨4096⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVLargePage) true none))}"
#eval IO.println s!"369|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedSize (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 2)))}"
#eval IO.println s!"370|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedSize (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) true none))}"
#eval IO.println s!"371|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedSize (_root_.Sel4Lean.Spec.ArchCapability.ASIDPoolCap ⟨4096⟩ (_root_.Sel4Lean.Spec.ASID.ASID 15000021067541002110)))}"
#eval IO.println s!"372|{showS (Sel4Lean.Spec.M.Object_ObjectType_RISCV64.capUntypedSize (_root_.Sel4Lean.Spec.ArchCapability.FrameCap ⟨7765918676081421445⟩ (_root_.Sel4Lean.Spec.VMRights.VMReadWrite) (_root_.Sel4Lean.Spec.VMPageSize.RISCVSmallPage) false (some ((_root_.Sel4Lean.Spec.ASID.ASID 9223372036854775808), (_root_.Sel4Lean.Spec.VPtr.VPtr 18446744073709551615)))))}"
#eval IO.println s!"373|{showS (Sel4Lean.Spec.M.Object_Structures.objBitsKO (_root_.Sel4Lean.Spec.KernelObject.KOUserData))}"
#eval IO.println s!"374|{showS (Sel4Lean.Spec.M.Object_Structures.objBitsKO (_root_.Sel4Lean.Spec.KernelObject.KOArch (_root_.Sel4Lean.Spec.ArchKernelObject.KOPTE (_root_.Sel4Lean.Spec.PTE.InvalidPTE))))}"
#eval IO.println s!"375|{showS (Sel4Lean.Spec.M.Object_Structures.objBitsKO (_root_.Sel4Lean.Spec.KernelObject.KOCTE (_root_.Sel4Lean.Spec.CTE.CTE (_root_.Sel4Lean.Spec.Capability.UntypedCap false ⟨18446743798831648768⟩ 0 5) (_root_.Sel4Lean.Spec.MDBNode.MDB ⟨18446743798831648768⟩ ⟨0⟩ true true))))}"
#eval IO.println s!"376|{showS (Sel4Lean.Spec.M.Object_Structures.objBitsKO (_root_.Sel4Lean.Spec.KernelObject.KOUserData))}"
#eval IO.println s!"377|{showS (Sel4Lean.Spec.M.Object_Structures.objBitsKO (_root_.Sel4Lean.Spec.KernelObject.KOCTE (_root_.Sel4Lean.Spec.CTE.CTE (_root_.Sel4Lean.Spec.Capability.Zombie ⟨4650277022584014665⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieTCB) 5) (_root_.Sel4Lean.Spec.MDBNode.MDB ⟨0⟩ ⟨18446743798831648768⟩ true true))))}"
#eval IO.println s!"378|{showS (Sel4Lean.Spec.M.Object_Structures.objBitsKO (_root_.Sel4Lean.Spec.KernelObject.KOUserData))}"
#eval IO.println s!"379|{showS (Sel4Lean.Spec.M.Object_Structures.dschDomain (7, 18446744073709551615))}"
#eval IO.println s!"380|{showS (Sel4Lean.Spec.M.Object_Structures.dschDomain (2, 14724384021782125956))}"
#eval IO.println s!"381|{showS (Sel4Lean.Spec.M.Object_Structures.dschDomain (7, 13565043686050396354))}"
#eval IO.println s!"382|{showS (Sel4Lean.Spec.M.Object_Structures.dschDomain (128, 9810138271054610628))}"
#eval IO.println s!"383|{showS (Sel4Lean.Spec.M.Object_Structures.dschDomain (255, 0))}"
#eval IO.println s!"384|{showS (Sel4Lean.Spec.M.Object_Structures.dschDomain (1, 16236456877958048376))}"
#eval IO.println s!"385|{showS (Sel4Lean.Spec.M.Object_Structures.dschLength (1, 2))}"
#eval IO.println s!"386|{showS (Sel4Lean.Spec.M.Object_Structures.dschLength (2, 9223372036854775808))}"
#eval IO.println s!"387|{showS (Sel4Lean.Spec.M.Object_Structures.dschLength (255, 11988219448054428301))}"
#eval IO.println s!"388|{showS (Sel4Lean.Spec.M.Object_Structures.dschLength (255, 9223372036854775808))}"
#eval IO.println s!"389|{showS (Sel4Lean.Spec.M.Object_Structures.dschLength (9, 2))}"
#eval IO.println s!"390|{showS (Sel4Lean.Spec.M.Object_Structures.dschLength (0, 7))}"
#eval IO.println s!"391|{showS (Sel4Lean.Spec.M.Object_Structures.isReceive (_root_.Sel4Lean.Spec.ThreadState.Restart))}"
#eval IO.println s!"392|{showS (Sel4Lean.Spec.M.Object_Structures.isReceive (_root_.Sel4Lean.Spec.ThreadState.BlockedOnReply))}"
#eval IO.println s!"393|{showS (Sel4Lean.Spec.M.Object_Structures.isReceive (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"394|{showS (Sel4Lean.Spec.M.Object_Structures.isReceive (_root_.Sel4Lean.Spec.ThreadState.Running))}"
#eval IO.println s!"395|{showS (Sel4Lean.Spec.M.Object_Structures.isReceive (_root_.Sel4Lean.Spec.ThreadState.BlockedOnSend ⟨18446743798831648768⟩ 11539295017510136707 true false true))}"
#eval IO.println s!"396|{showS (Sel4Lean.Spec.M.Object_Structures.isReceive (_root_.Sel4Lean.Spec.ThreadState.BlockedOnReply))}"
#eval IO.println s!"397|{showS (Sel4Lean.Spec.M.Object_Structures.isSend (_root_.Sel4Lean.Spec.ThreadState.Inactive))}"
#eval IO.println s!"398|{showS (Sel4Lean.Spec.M.Object_Structures.isSend (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"399|{showS (Sel4Lean.Spec.M.Object_Structures.isSend (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"400|{showS (Sel4Lean.Spec.M.Object_Structures.isSend (_root_.Sel4Lean.Spec.ThreadState.Running))}"
#eval IO.println s!"401|{showS (Sel4Lean.Spec.M.Object_Structures.isSend (_root_.Sel4Lean.Spec.ThreadState.Inactive))}"
#eval IO.println s!"402|{showS (Sel4Lean.Spec.M.Object_Structures.isSend (_root_.Sel4Lean.Spec.ThreadState.BlockedOnReply))}"
#eval IO.println s!"403|{showS (Sel4Lean.Spec.M.Object_Structures.isReply (_root_.Sel4Lean.Spec.ThreadState.BlockedOnReceive ⟨4096⟩ false))}"
#eval IO.println s!"404|{showS (Sel4Lean.Spec.M.Object_Structures.isReply (_root_.Sel4Lean.Spec.ThreadState.BlockedOnReceive ⟨433127922476178377⟩ false))}"
#eval IO.println s!"405|{showS (Sel4Lean.Spec.M.Object_Structures.isReply (_root_.Sel4Lean.Spec.ThreadState.IdleThreadState))}"
#eval IO.println s!"406|{showS (Sel4Lean.Spec.M.Object_Structures.isReply (_root_.Sel4Lean.Spec.ThreadState.BlockedOnNotification ⟨8860868559124403862⟩))}"
#eval IO.println s!"407|{showS (Sel4Lean.Spec.M.Object_Structures.isReply (_root_.Sel4Lean.Spec.ThreadState.Restart))}"
#eval IO.println s!"408|{showS (Sel4Lean.Spec.M.Object_Structures.isReply (_root_.Sel4Lean.Spec.ThreadState.BlockedOnNotification ⟨18446743798831648768⟩))}"
#eval IO.println s!"409|{showS (Sel4Lean.Spec.M.Object_Structures.maxFreeIndex 63)}"
#eval IO.println s!"410|{showS (Sel4Lean.Spec.M.Object_Structures.maxFreeIndex 63)}"
#eval IO.println s!"411|{showS (Sel4Lean.Spec.M.Object_Structures.maxFreeIndex 8)}"
#eval IO.println s!"412|{showS (Sel4Lean.Spec.M.Object_Structures.maxFreeIndex 5)}"
#eval IO.println s!"413|{showS (Sel4Lean.Spec.M.Object_Structures.maxFreeIndex 1)}"
#eval IO.println s!"414|{showS (Sel4Lean.Spec.M.Object_Structures.maxFreeIndex 5)}"
#eval IO.println s!"415|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeRef ⟨4096⟩ 3)}"
#eval IO.println s!"416|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeRef ⟨4096⟩ 0)}"
#eval IO.println s!"417|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeRef ⟨11750759284440955675⟩ 3)}"
#eval IO.println s!"418|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeRef ⟨4096⟩ 31)}"
#eval IO.println s!"419|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeRef ⟨0⟩ 12)}"
#eval IO.println s!"420|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeRef ⟨0⟩ 63)}"
#eval IO.println s!"421|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeIndex ⟨5114351736500806037⟩ ⟨2794840795817871868⟩)}"
#eval IO.println s!"422|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeIndex ⟨11103261702100655379⟩ ⟨0⟩)}"
#eval IO.println s!"423|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeIndex ⟨0⟩ ⟨3387423451175770610⟩)}"
#eval IO.println s!"424|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeIndex ⟨18446743798831648768⟩ ⟨4096⟩)}"
#eval IO.println s!"425|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeIndex ⟨18446743798831648768⟩ ⟨530549124295952605⟩)}"
#eval IO.println s!"426|{showS (Sel4Lean.Spec.M.Object_Structures.getFreeIndex ⟨3789592007004028616⟩ ⟨0⟩)}"
#eval IO.println s!"427|{showS (Sel4Lean.Spec.M.Object_Structures.untypedZeroRange (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.PageTableCap ⟨14050077530989943562⟩ none)))}"
#eval IO.println s!"428|{showS (Sel4Lean.Spec.M.Object_Structures.untypedZeroRange (_root_.Sel4Lean.Spec.Capability.Zombie ⟨18446743798831648768⟩ (_root_.Sel4Lean.Spec.ZombieType.ZombieCNode 5) 2))}"
#eval IO.println s!"429|{showS (Sel4Lean.Spec.M.Object_Structures.untypedZeroRange (_root_.Sel4Lean.Spec.Capability.ArchObjectCap (_root_.Sel4Lean.Spec.ArchCapability.ASIDControlCap)))}"
#eval IO.println s!"430|{showS (Sel4Lean.Spec.M.Object_Structures.untypedZeroRange (_root_.Sel4Lean.Spec.Capability.NotificationCap ⟨18446743798831648768⟩ 0 false true))}"
#eval IO.println s!"431|{showS (Sel4Lean.Spec.M.Object_Structures.untypedZeroRange (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨0⟩ 31 1 1))}"
#eval IO.println s!"432|{showS (Sel4Lean.Spec.M.Object_Structures.untypedZeroRange (_root_.Sel4Lean.Spec.Capability.CNodeCap ⟨0⟩ 12 18446744073709551615 8))}"
#eval IO.println s!"433|{showS (Sel4Lean.Spec.M.Object_Structures.tcbFlagToWord (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled))}"
#eval IO.println s!"434|{showS (Sel4Lean.Spec.M.Object_Structures.tcbFlagToWord (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled))}"
#eval IO.println s!"435|{showS (Sel4Lean.Spec.M.Object_Structures.tcbFlagToWord (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled))}"
#eval IO.println s!"436|{showS (Sel4Lean.Spec.M.Object_Structures.tcbFlagToWord (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled))}"
#eval IO.println s!"437|{showS (Sel4Lean.Spec.M.Object_Structures.tcbFlagToWord (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled))}"
#eval IO.println s!"438|{showS (Sel4Lean.Spec.M.Object_Structures.tcbFlagToWord (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled))}"
#eval IO.println s!"439|{showS (Sel4Lean.Spec.M.Object_Structures.isFlagSet (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled) 0)}"
#eval IO.println s!"440|{showS (Sel4Lean.Spec.M.Object_Structures.isFlagSet (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled) 522394163779903744)}"
#eval IO.println s!"441|{showS (Sel4Lean.Spec.M.Object_Structures.isFlagSet (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled) 18446744073709551615)}"
#eval IO.println s!"442|{showS (Sel4Lean.Spec.M.Object_Structures.isFlagSet (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled) 1)}"
#eval IO.println s!"443|{showS (Sel4Lean.Spec.M.Object_Structures.isFlagSet (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled) 0)}"
#eval IO.println s!"444|{showS (Sel4Lean.Spec.M.Object_Structures.isFlagSet (_root_.Sel4Lean.Spec.TcbFlag.FpuDisabled) 9223372036854775808)}"
#eval IO.println s!"445|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (_root_.Sel4Lean.Spec.ASID.ASID 17917349023871268036))}"
#eval IO.println s!"446|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (_root_.Sel4Lean.Spec.ASID.ASID 1))}"
#eval IO.println s!"447|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (_root_.Sel4Lean.Spec.ASID.ASID 7))}"
#eval IO.println s!"448|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (_root_.Sel4Lean.Spec.ASID.ASID 1))}"
#eval IO.println s!"449|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (_root_.Sel4Lean.Spec.ASID.ASID 18446744073709551615))}"
#eval IO.println s!"450|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (_root_.Sel4Lean.Spec.ASID.ASID 10288444642535322734))}"
#eval IO.println s!"451|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.parseTimeArg 5 [])}"
#eval IO.println s!"452|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.parseTimeArg 5 [])}"
#eval IO.println s!"453|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.parseTimeArg 2 [2])}"
#eval IO.println s!"454|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.parseTimeArg 8 [])}"
#eval IO.println s!"455|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.parseTimeArg 5 [])}"
#eval IO.println s!"456|{showS (Sel4Lean.Spec.M.Object_Structures_RISCV64.parseTimeArg 3 [])}"
#eval IO.println s!"457|{showS (Sel4Lean.Spec.M.Object_TCB.sanitiseRegister false (_root_.Sel4Lean.Spec.Register.Register (_root_.Sel4Lean.Spec.RISCV64.Register.S2)) 1)}"
#eval IO.println s!"458|{showS (Sel4Lean.Spec.M.Object_TCB.sanitiseRegister true (_root_.Sel4Lean.Spec.Register.Register (_root_.Sel4Lean.Spec.RISCV64.Register.S9)) 1)}"
#eval IO.println s!"459|{showS (Sel4Lean.Spec.M.Object_TCB.sanitiseRegister true (_root_.Sel4Lean.Spec.Register.Register (_root_.Sel4Lean.Spec.RISCV64.Register.S9)) 3742993907310110422)}"
#eval IO.println s!"460|{showS (Sel4Lean.Spec.M.Object_TCB.sanitiseRegister true (_root_.Sel4Lean.Spec.Register.Register (_root_.Sel4Lean.Spec.RISCV64.Register.SSTATUS)) 18446744073709551615)}"
#eval IO.println s!"461|{showS (Sel4Lean.Spec.M.Object_TCB.sanitiseRegister false (_root_.Sel4Lean.Spec.Register.Register (_root_.Sel4Lean.Spec.RISCV64.Register.T4)) 18446744073709551615)}"
#eval IO.println s!"462|{showS (Sel4Lean.Spec.M.Object_TCB.sanitiseRegister true (_root_.Sel4Lean.Spec.Register.Register (_root_.Sel4Lean.Spec.RISCV64.Register.A1)) 7)}"
#eval IO.println s!"463|{showS (Sel4Lean.Spec.M.Object_TCB_RISCV64.sanitiseRegister true (_root_.Sel4Lean.Spec.RISCV64.Register.A6) 6226593157583516434)}"
#eval IO.println s!"464|{showS (Sel4Lean.Spec.M.Object_TCB_RISCV64.sanitiseRegister true (_root_.Sel4Lean.Spec.RISCV64.Register.S10) 0)}"
#eval IO.println s!"465|{showS (Sel4Lean.Spec.M.Object_TCB_RISCV64.sanitiseRegister false (_root_.Sel4Lean.Spec.RISCV64.Register.S2) 1)}"
#eval IO.println s!"466|{showS (Sel4Lean.Spec.M.Object_TCB_RISCV64.sanitiseRegister true (_root_.Sel4Lean.Spec.RISCV64.Register.S3) 1)}"
#eval IO.println s!"467|{showS (Sel4Lean.Spec.M.Object_TCB_RISCV64.sanitiseRegister true (_root_.Sel4Lean.Spec.RISCV64.Register.S1) 1)}"
#eval IO.println s!"468|{showS (Sel4Lean.Spec.M.Object_TCB_RISCV64.sanitiseRegister false (_root_.Sel4Lean.Spec.RISCV64.Register.S0) 18446744073709551615)}"
#eval IO.println s!"469|{showS (Sel4Lean.Spec.M.Object_Untyped.alignUp 0 12)}"
#eval IO.println s!"470|{showS (Sel4Lean.Spec.M.Object_Untyped.alignUp 7 63)}"
#eval IO.println s!"471|{showS (Sel4Lean.Spec.M.Object_Untyped.alignUp 1 3)}"
#eval IO.println s!"472|{showS (Sel4Lean.Spec.M.Object_Untyped.alignUp 7 3)}"
#eval IO.println s!"473|{showS (Sel4Lean.Spec.M.Object_Untyped.alignUp 18446744073709551615 3)}"
#eval IO.println s!"474|{showS (Sel4Lean.Spec.M.Object_Untyped.alignUp 9223372036854775808 63)}"
#eval IO.println s!"475|{showS (Sel4Lean.Spec.M.Object_Untyped.canonicalAddressAssert ⟨18446743798831648768⟩)}"
#eval IO.println s!"476|{showS (Sel4Lean.Spec.M.Object_Untyped.canonicalAddressAssert ⟨18446743798831648768⟩)}"
#eval IO.println s!"477|{showS (Sel4Lean.Spec.M.Object_Untyped.canonicalAddressAssert ⟨0⟩)}"
#eval IO.println s!"478|{showS (Sel4Lean.Spec.M.Object_Untyped.canonicalAddressAssert ⟨290836296047196881⟩)}"
#eval IO.println s!"479|{showS (Sel4Lean.Spec.M.Object_Untyped.canonicalAddressAssert ⟨0⟩)}"
#eval IO.println s!"480|{showS (Sel4Lean.Spec.M.Object_Untyped.canonicalAddressAssert ⟨0⟩)}"
