theory Values
  imports ExecSpec.API_H ExecSpec.ArchIntermediate_H
begin

text \<open>Evaluate the differential-test cases in l4v's executable spec. Each case is a constant applied to
numerals (built as typed terms, not parsed) and evaluated with Isabelle's @{command value} machinery.
Generated by tools/hs2lean/isagate.py. Output: GATE_OUT/values.tsv\<close>

ML \<open>
  datatype arg = N of int | B of bool
  val out = Path.explode (getenv "GATE_OUT") + Path.basic "values.tsv"
  val ctxt = @{context}
  val thy = @{theory}
  fun mono T = Term.map_atyps (fn _ => @{typ unit}) T
  fun mk_arg T (N n) = HOLogic.mk_number T n
    | mk_arg _ (B b) = if b then @{term True} else @{term False}
  fun plain t = Print_Mode.setmp [] (fn () => Syntax.string_of_term ctxt t) ()
                |> String.translate (fn #"\n" => " " | c => str c)
  (* l4v defines spec constants with `defs` (no code equations): unfold them with their definitional
     axioms (a theorem-producing rewrite), then evaluate the remaining arithmetic *)
  val space = Consts.space_of (Sign.consts_of thy)
  (* only the spec's own constants: unfolding Word_Lib's definitions (word +, shifts) would leave the
     code generator's representation and blow up *)
  fun spec_const c = String.isPrefix "ExecSpec." (#theory_long_name (Name_Space.the_entry space c))
                     handle ERROR _ => false
  val def_tab =
    fold (fn (_, th) => fn tab =>
        (case Thm.prop_of th of
          Const (@{const_name Pure.eq}, _) $ lhs $ _ =>
            (case head_of lhs of
              Const (c, _) => if spec_const c then Symtab.cons_list (c, th) tab else tab
            | _ => tab)
        | _ => tab))
      (Thm.all_axioms_of thy) Symtab.empty
  fun consts_in t = Term.fold_aterms (fn Const (c, _) => insert (op =) c | _ => I) t []
  fun unfold t n =
    let
      val defs = maps (Symtab.lookup_list def_tab) (consts_in t)
    in
      if null defs orelse n = 0 then t
      else
        let
          val ctxt' = put_simpset HOL_basic_ss ctxt addsimps defs
          val t' = Thm.rhs_of (Simplifier.rewrite ctxt' (Thm.cterm_of ctxt t)) |> Thm.term_of
        in if t' aconv t then t else unfold t' (n - 1) end
    end
  fun eval1 (c, args) =
    let
      (* an abbreviation (e.g. Platform's `fromPAddr == id`) is not a logical constant: use its rhs *)
      val (T, head) =
        (case try (Consts.the_abbreviation (Sign.consts_of thy)) c of
          SOME (ty, rhs) => (mono ty, Term.map_types mono rhs)
        | NONE => let val ty = mono (Sign.the_const_type thy c) in (ty, Const (c, ty)) end)
      val t = list_comb (head, map2 mk_arg (take (length args) (binder_types T)) args)
      val value = Timeout.apply (Time.fromSeconds 30) (Value_Command.value ctxt)
      (* the default simpset (Word_Lib's lemmas): e.g. `finiteBitSize (undefined :: 64 word) = 64`, which
         code evaluation cannot do (it evaluates `undefined` strictly) *)
      fun simp u = Thm.rhs_of (Timeout.apply (Time.fromSeconds 30)
                     (Simplifier.rewrite (ctxt addsimps @{thms word_size})) (Thm.cterm_of ctxt u)) |> Thm.term_of
      fun numeral u = can HOLogic.dest_number u orelse u aconv @{term True} orelse u aconv @{term False}
    in
      (case Exn.result value t of
        Exn.Res v => plain v
      | Exn.Exn _ =>
          let val u = unfold t 12 in
            (case Exn.result value u of
              Exn.Res v => plain v
            | Exn.Exn _ => let val w = simp u in if numeral w then plain w else plain (value w) end)
          end)
    end
  (* Exn.result: catches evaluation failures but lets interrupts through *)
  fun ev (id, c, args) =
    (case Exn.result eval1 (c, args) of
      Exn.Res r => id ^ "\t" ^ r
    | Exn.Exn e => id ^ "\tERR " ^ hd (split_lines (Runtime.exn_message e) @ [""]))
  val cases = [
   ("1", "State_H.RISCV64_H.wordBits", []),
   ("2", "State_H.wordSize", []),
   ("3", "State_H.wordRadix", []),
   ("4", "ArchTypes_H.RISCV64_H.tcbBlockSizeBits", []),
   ("5", "ArchTypes_H.epSizeBits", []),
   ("6", "ArchTypes_H.ntfnSizeBits", []),
   ("7", "ArchTypes_H.cteSizeBits", []),
   ("8", "Config_H.minFreeSlots", []),
   ("9", "Config_H.minSmallBlocks", []),
   ("10", "Config_H.rootCNodeSize", []),
   ("11", "Kernel_Config.timeSlice", []),
   ("12", "Kernel_Config.numDomains", []),
   ("13", "Config_H.numPriorities", []),
   ("14", "Kernel_Config.retypeFanOutLimit", []),
   ("15", "Kernel_Config.resetChunkBits", []),
   ("16", "ThreadDecls_H.invertL1Index", [N 0]),
   ("17", "ThreadDecls_H.invertL1Index", [N 1]),
   ("18", "ThreadDecls_H.invertL1Index", [N 2]),
   ("19", "ThreadDecls_H.invertL1Index", [N 3]),
   ("20", "ThreadDecls_H.invertL1Index", [N 8]),
   ("21", "ThreadDecls_H.invertL1Index", [N 12]),
   ("22", "ThreadDecls_H.invertL1Index", [N 31]),
   ("23", "ThreadDecls_H.invertL1Index", [N 32]),
   ("24", "ThreadDecls_H.prioToL1Index", [N 0]),
   ("25", "ThreadDecls_H.prioToL1Index", [N 1]),
   ("26", "ThreadDecls_H.prioToL1Index", [N 2]),
   ("27", "ThreadDecls_H.prioToL1Index", [N 7]),
   ("28", "ThreadDecls_H.prioToL1Index", [N 255]),
   ("29", "ThreadDecls_H.prioToL1Index", [N 128]),
   ("30", "ThreadDecls_H.prioToL1Index", [N 158]),
   ("31", "ThreadDecls_H.prioToL1Index", [N 111]),
   ("32", "ThreadDecls_H.l1IndexToPrio", [N 0]),
   ("33", "ThreadDecls_H.l1IndexToPrio", [N 1]),
   ("34", "ThreadDecls_H.l1IndexToPrio", [N 2]),
   ("35", "ThreadDecls_H.l1IndexToPrio", [N 3]),
   ("36", "ThreadDecls_H.l1IndexToPrio", [N 8]),
   ("37", "ThreadDecls_H.l1IndexToPrio", [N 12]),
   ("38", "ThreadDecls_H.l1IndexToPrio", [N 31]),
   ("39", "ThreadDecls_H.l1IndexToPrio", [N 32]),
   ("40", "ArchVSpaceDecls_H.RISCV64_H.ipcBufferSizeBits", []),
   ("41", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 0]),
   ("42", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 1]),
   ("43", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 2]),
   ("44", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 3]),
   ("45", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 8]),
   ("46", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 12]),
   ("47", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 31]),
   ("48", "ArchVSpaceDecls_H.RISCV64_H.ptBitsLeft", [N 32]),
   ("49", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 0, N 0]),
   ("50", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 1, N 1]),
   ("51", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 2, N 2]),
   ("52", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 3, N 7]),
   ("53", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 8, N 4095]),
   ("54", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 12, N 4096]),
   ("55", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 31, N 18446744073709551615]),
   ("56", "ArchVSpaceDecls_H.RISCV64_H.ptIndex", [N 32, N 9223372036854775808]),
   ("57", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 0, N 0, N 0]),
   ("58", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 1, N 1, N 1]),
   ("59", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 2, N 2, N 2]),
   ("60", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 3, N 7, N 7]),
   ("61", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 8, N 4095, N 4095]),
   ("62", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 12, N 4096, N 4096]),
   ("63", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 31, N 18446744073709551615, N 18446744073709551615]),
   ("64", "ArchVSpaceDecls_H.RISCV64_H.ptSlotIndex", [N 32, N 9223372036854775808, N 9223372036854775808]),
   ("65", "Platform.RISCV64.pptrBaseOffset", []),
   ("66", "Platform.RISCV64.ptrFromPAddr", [N 0]),
   ("67", "Platform.RISCV64.ptrFromPAddr", [N 1]),
   ("68", "Platform.RISCV64.ptrFromPAddr", [N 2]),
   ("69", "Platform.RISCV64.ptrFromPAddr", [N 7]),
   ("70", "Platform.RISCV64.ptrFromPAddr", [N 4095]),
   ("71", "Platform.RISCV64.ptrFromPAddr", [N 4096]),
   ("72", "Platform.RISCV64.ptrFromPAddr", [N 18446744073709551615]),
   ("73", "Platform.RISCV64.ptrFromPAddr", [N 9223372036854775808]),
   ("74", "Platform.RISCV64.addrFromPPtr", [N 0]),
   ("75", "Platform.RISCV64.addrFromPPtr", [N 1]),
   ("76", "Platform.RISCV64.addrFromPPtr", [N 2]),
   ("77", "Platform.RISCV64.addrFromPPtr", [N 7]),
   ("78", "Platform.RISCV64.addrFromPPtr", [N 4095]),
   ("79", "Platform.RISCV64.addrFromPPtr", [N 4096]),
   ("80", "Platform.RISCV64.addrFromPPtr", [N 18446744073709551615]),
   ("81", "Platform.RISCV64.addrFromPPtr", [N 9223372036854775808]),
   ("82", "Platform.RISCV64.addrFromKPPtr", [N 0]),
   ("83", "Platform.RISCV64.addrFromKPPtr", [N 1]),
   ("84", "Platform.RISCV64.addrFromKPPtr", [N 2]),
   ("85", "Platform.RISCV64.addrFromKPPtr", [N 7]),
   ("86", "Platform.RISCV64.addrFromKPPtr", [N 4095]),
   ("87", "Platform.RISCV64.addrFromKPPtr", [N 4096]),
   ("88", "Platform.RISCV64.addrFromKPPtr", [N 18446744073709551615]),
   ("89", "Platform.RISCV64.addrFromKPPtr", [N 9223372036854775808]),
   ("90", "MachineTypes.RISCV64.pageBits", []),
   ("91", "Platform.RISCV64.pageColourBits", []),
   ("92", "State_H.RISCV64_H.nullPointer", []),
   ("93", "Kernel_Config.config_HAVE_FPU", []),
   ("94", "Hardware_H.RISCV64_H.fromPAddr", [N 0]),
   ("95", "Hardware_H.RISCV64_H.fromPAddr", [N 1]),
   ("96", "Hardware_H.RISCV64_H.fromPAddr", [N 2]),
   ("97", "Hardware_H.RISCV64_H.fromPAddr", [N 7]),
   ("98", "Hardware_H.RISCV64_H.fromPAddr", [N 4095]),
   ("99", "Hardware_H.RISCV64_H.fromPAddr", [N 4096]),
   ("100", "Hardware_H.RISCV64_H.fromPAddr", [N 18446744073709551615]),
   ("101", "Hardware_H.RISCV64_H.fromPAddr", [N 9223372036854775808]),
   ("102", "Platform.RISCV64.paddrBase", []),
   ("103", "Platform.RISCV64.pptrBase", []),
   ("104", "Platform.RISCV64.pptrTop", []),
   ("105", "Platform.RISCV64.kernelELFPAddrBase", []),
   ("106", "Platform.RISCV64.kernelELFBase", []),
   ("107", "Platform.RISCV64.pptrUserTop", []),
   ("108", "Platform.RISCV64.ptrFromPAddr", [N 0]),
   ("109", "Platform.RISCV64.ptrFromPAddr", [N 1]),
   ("110", "Platform.RISCV64.ptrFromPAddr", [N 2]),
   ("111", "Platform.RISCV64.ptrFromPAddr", [N 7]),
   ("112", "Platform.RISCV64.ptrFromPAddr", [N 4095]),
   ("113", "Platform.RISCV64.ptrFromPAddr", [N 4096]),
   ("114", "Platform.RISCV64.ptrFromPAddr", [N 18446744073709551615]),
   ("115", "Platform.RISCV64.ptrFromPAddr", [N 9223372036854775808]),
   ("116", "Platform.RISCV64.addrFromPPtr", [N 0]),
   ("117", "Platform.RISCV64.addrFromPPtr", [N 1]),
   ("118", "Platform.RISCV64.addrFromPPtr", [N 2]),
   ("119", "Platform.RISCV64.addrFromPPtr", [N 7]),
   ("120", "Platform.RISCV64.addrFromPPtr", [N 4095]),
   ("121", "Platform.RISCV64.addrFromPPtr", [N 4096]),
   ("122", "Platform.RISCV64.addrFromPPtr", [N 18446744073709551615]),
   ("123", "Platform.RISCV64.addrFromPPtr", [N 9223372036854775808]),
   ("124", "Platform.RISCV64.addrFromKPPtr", [N 0]),
   ("125", "Platform.RISCV64.addrFromKPPtr", [N 1]),
   ("126", "Platform.RISCV64.addrFromKPPtr", [N 2]),
   ("127", "Platform.RISCV64.addrFromKPPtr", [N 7]),
   ("128", "Platform.RISCV64.addrFromKPPtr", [N 4095]),
   ("129", "Platform.RISCV64.addrFromKPPtr", [N 4096]),
   ("130", "Platform.RISCV64.addrFromKPPtr", [N 18446744073709551615]),
   ("131", "Platform.RISCV64.addrFromKPPtr", [N 9223372036854775808]),
   ("132", "MachineTypes.RISCV64.pageBits", []),
   ("133", "MachineTypes.RISCV64.ptTranslationBits", []),
   ("134", "Hardware_H.RISCV64_H.pteBits", []),
   ("135", "Hardware_H.RISCV64_H.ptBits", []),
   ("136", "Platform.RISCV64.pageColourBits", []),
   ("137", "Kernel_Config.physBase", []),
   ("138", "Platform.RISCV64.pageColourBits", []),
   ("139", "MachineTypes.RISCV64.sstatusSPIE", []),
   ("140", "ArchStateData_H.RISCV64_H.maxPTLevel", []),
   ("141", "RetypeDecls_H.badgeBits", []),
   ("142", "ArchRetypeDecls_H.RISCV64_H.cteRightsBits", []),
   ("143", "ArchRetypeDecls_H.RISCV64_H.cteGuardBits", []),
   ("144", "ArchRetypeDecls_H.RISCV64_H.asidPoolBits", []),
   ("145", "ArchStructures_H.RISCV64_H.minUntypedSizeBits", []),
   ("146", "ArchStructures_H.RISCV64_H.maxUntypedSizeBits", []),
   ("147", "ArchStructures_H.RISCV64_H.asidHighBits", []),
   ("148", "ArchStructures_H.RISCV64_H.asidLowBits", []),
   ("149", "ArchStructures_H.RISCV64_H.asidBits", []),
   ("150", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 0]),
   ("151", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 1]),
   ("152", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 2]),
   ("153", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 7]),
   ("154", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 4095]),
   ("155", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 4096]),
   ("156", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 18446744073709551615]),
   ("157", "ArchStructures_H.RISCV64_H.asidHighBitsOf", [N 9223372036854775808]),
   ("158", "Structs_B.timeArgLen", [])]
  val _ = File.write out (cat_lines (map ev cases) ^ "\n")
  val _ = writeln ("GATE values: " ^ string_of_int (length cases))
\<close>

end
