-- SPDX-License-Identifier: GPL-2.0-only (derived from seL4/l4v, https://github.com/seL4/l4v)
import Sel4Lean.Corres
import Sel4Lean.Tactic.WP
import Sel4Lean.Exec.Gen.Notification
import Sel4Lean.Abstract.IpcCancel

/-!
# C4: `cancelSignal_corres` in Lean

Port of l4v `proof/refine/IpcCancel_R.thy:307`:

```
lemma cancelSignal_corres:
  "corres dc
          (invs and st_tcb_at ((=) (Structures_A.BlockedOnNotification ntfn)) t)
          (invs' and st_tcb_at' ((=) (BlockedOnNotification ntfn)) t)
          (cancel_signal t ntfn)
          (cancelSignal t ntfn)"
```

The abstract side is `Abstract/IpcCancel.lean` (hand-translated); the executable side is
`Exec/Gen/Notification.lean`, **generated by hs2lean and unedited**.

## Trust base of this slice

Everything outside the slice is opaque, so the lemmas l4v proves about it elsewhere are **assumed** here,
collected in `CancelSignalAssumptions`. Each field names its l4v source. Walk replaces these with proofs.
-/

namespace Sel4Lean.Refine
open NondetM Sel4Lean.Exec

noncomputable section

abbrev AState := Sel4Lean.Abstract.State
abbrev ObjRef := Sel4Lean.Abstract.ObjRef

/-! ## Relations and predicates (l4v `StateRelation.thy`, invariant definitions: opaque or ported) -/

/-- l4v `state_relation` (StateRelation.thy): opaque for the slice. -/
opaque state_relation : AState → KernelState → Prop

/-- l4v `corres ≡ corres_underlying state_relation False True` (Corres.thy:13):
the abstract side may fail; the executable side must not. -/
abbrev corres {α β : Type} (r : α → β → Prop) (P : AState → Prop) (P' : KernelState → Prop)
    (m : Sel4Lean.Abstract.SMonad α) (m' : Kernel β) : Prop :=
  corresUnderlying state_relation False True r P P' m m'

/-- l4v `dc` ("don't care" return relation). -/
def dc {α β : Type} : α → β → Prop := fun _ _ => True

/-- Isabelle uses machine words for pointers on both sides; the Lean executable spec tags them. -/
def toPtr {α : Type} (r : ObjRef) : PPtr α := ⟨r⟩

theorem toPtr_injective {α : Type} {a b : ObjRef} (h : (toPtr a : PPtr α) = toPtr b) : a = b :=
  congrArg PPtr.ptr h

/-- l4v `ntfn_relation` (StateRelation.thy), object part. -/
def ntfnObj_relation : Sel4Lean.Abstract.Ntfn → NTFN → Prop
  | .IdleNtfn, n' => n' = .IdleNtfn
  | .WaitingNtfn q, n' => n' = .WaitingNtfn (q.map toPtr)
  | .ActiveNtfn b, n' => n' = .ActiveNtfn b

/-- l4v `ntfn_relation` (StateRelation.thy). -/
def ntfn_relation (n : Sel4Lean.Abstract.Notification) (n' : Notification) : Prop :=
  ntfnObj_relation n.ntfn_obj n'.ntfnObj ∧ n.ntfn_bound_tcb.map toPtr = n'.ntfnBoundTCB

/-- Cases of l4v's `thread_state_relation` that need payload relations outside the slice. -/
opaque thread_state_relation_rest : Sel4Lean.Abstract.ThreadState → ThreadState → Prop

/-- l4v `thread_state_relation` (StateRelation.thy, primrec). -/
def thread_state_relation : Sel4Lean.Abstract.ThreadState → ThreadState → Prop
  | .Running, ts' => ts' = .Running
  | .Restart, ts' => ts' = .Restart
  | .Inactive, ts' => ts' = .Inactive
  | .IdleThreadState, ts' => ts' = .IdleThreadState
  | .BlockedOnReply, ts' => ts' = .BlockedOnReply
  | .BlockedOnNotification n, ts' => ts' = .BlockedOnNotification (toPtr n)
  | ts, ts' => thread_state_relation_rest ts ts'

-- Invariants and object predicates (AInvs / Invariants_H): opaque for the slice.
opaque invs : AState → Prop
opaque invs' : KernelState → Prop
opaque ntfn_at : ObjRef → AState → Prop
opaque ntfn_at' : PPtr Notification → KernelState → Prop
opaque tcb_at : ObjRef → AState → Prop
opaque pspace_aligned : AState → Prop
opaque pspace_distinct : AState → Prop
opaque st_tcb_at : (Sel4Lean.Abstract.ThreadState → Prop) → ObjRef → AState → Prop
opaque st_tcb_at' : (ThreadState → Prop) → PPtr TCB → KernelState → Prop

/-! ## The assumed lemmas -/

/-- What `cancelSignal_corres` uses from the rest of l4v. Proved there; assumed here. -/
structure CancelSignalAssumptions : Prop where
  /-- KHeap_R.thy:904 -/
  getNotification_corres : ∀ p, corres ntfn_relation (ntfn_at p) (ntfn_at' (toPtr p))
    (Sel4Lean.Abstract.get_notification p) (getNotification (toPtr p))
  /-- KHeap_R.thy:1742 -/
  setNotification_corres : ∀ p n n', ntfn_relation n n' →
    corres dc (ntfn_at p) (ntfn_at' (toPtr p))
      (Sel4Lean.Abstract.set_notification p n) (setNotification (toPtr p) n')
  /-- TcbAcc_R.thy:2931 -/
  setThreadState_corres : ∀ t ts ts', thread_state_relation ts ts' →
    corres dc (fun s => tcb_at t s ∧ pspace_aligned s ∧ pspace_distinct s) (fun _ => True)
      (Sel4Lean.Abstract.set_thread_state t ts) (setThreadState ts' (toPtr t))
  /-- getters do not change the state (l4v `get_simple_ko_inv`, `getObject_inv`) -/
  get_notification_inv : ∀ p (P : AState → Prop),
    ⟪P⟫ (Sel4Lean.Abstract.get_notification p) ⟪fun _ => P⟫
  getNotification_inv : ∀ p (P : KernelState → Prop), ⟪P⟫ (getNotification p) ⟪fun _ => P⟫
  /-- `set_notification` preserves what `set_thread_state` needs (l4v `set_simple_ko` wp rules) -/
  set_notification_tcb : ∀ p n t,
    ⟪fun s => tcb_at t s ∧ pspace_aligned s ∧ pspace_distinct s⟫ (Sel4Lean.Abstract.set_notification p n)
    ⟪fun _ s => tcb_at t s ∧ pspace_aligned s ∧ pspace_distinct s⟫
  /-- from `invs` and the blocked thread: the objects exist (l4v `invs_valid_objs`, `st_tcb_at_tcb_at`, …) -/
  invs_blocked : ∀ s t p, invs s → st_tcb_at (· = .BlockedOnNotification p) t s →
    ntfn_at p s ∧ tcb_at t s ∧ pspace_aligned s ∧ pspace_distinct s
  invs'_blocked : ∀ s t p, invs' s → st_tcb_at' (· = .BlockedOnNotification (toPtr p)) (toPtr t) s →
    ntfn_at' (toPtr p) s
  /-- a thread blocked on a notification is in its wait queue (l4v `sym_refs_st_tcb_atD'`) -/
  getNotification_waiting : ∀ t p,
    ⟪fun s => invs' s ∧ st_tcb_at' (· = .BlockedOnNotification (toPtr p)) (toPtr t) s⟫
      (getNotification (toPtr p))
    ⟪fun n _ => ∃ q, n.ntfnObj = .WaitingNtfn q⟫

/-! ## Library lemmas -/

/-- l4v `corres_gen_asm2`: a pure fact in the executable guard can be assumed. -/
theorem corres_gen_asm2 {σ τ α β : Type} {sr : σ → τ → Prop} {nf nf' : Prop} {r : α → β → Prop}
    {P : σ → Prop} {P' : τ → Prop} {F : Prop} {f : NondetM σ α} {g : NondetM τ β}
    (h : F → corresUnderlying sr nf nf' r P P' f g) :
    corresUnderlying sr nf nf' r P (fun s => P' s ∧ F) f g :=
  fun s s' hs hP hP' hnf => h hP'.2 s s' hs hP hP'.1 hnf

/-- Erasing commutes with tagging pointers (Isabelle needs no such lemma: it has no tags). -/
theorem erase_map_toPtr {α : Type} (q : List ObjRef) (t : ObjRef) :
    (q.map (toPtr (α := α))).erase (toPtr t) = (q.erase t).map toPtr := by
  induction q with
  | nil => rfl
  | cons x xs ih =>
    by_cases h : x = t
    · subst h; simp [List.erase_cons_head]
    · have h' : (toPtr x : PPtr α) ≠ toPtr t := fun e => h (toPtr_injective e)
      simp [h, h', ih]

/-! ## The lemma -/

theorem cancelSignal_corres (H : CancelSignalAssumptions) (t ntfn : ObjRef) :
    corres dc
      (fun s => invs s ∧ st_tcb_at (· = .BlockedOnNotification ntfn) t s)
      (fun s => invs' s ∧ st_tcb_at' (· = .BlockedOnNotification (toPtr ntfn)) (toPtr t) s)
      (Sel4Lean.Abstract.cancel_signal t ntfn)
      (cancelSignal (toPtr t) (toPtr ntfn)) := by
  unfold Sel4Lean.Abstract.cancel_signal cancelSignal
  refine corres_guard_imp
    (corres_split (H.getNotification_corres ntfn)
      (R := fun _ s => tcb_at t s ∧ pspace_aligned s ∧ pspace_distinct s ∧ ntfn_at ntfn s)
      (R' := fun n s => ntfn_at' (toPtr ntfn) s ∧ ∃ q, n.ntfnObj = .WaitingNtfn q)
      (fun n n' hrel => ?_)
      (H.get_notification_inv ntfn _)
      (hoare_strengthen_post
        (hoare_conj (H.getNotification_inv (toPtr ntfn) (ntfn_at' (toPtr ntfn)))
                    (H.getNotification_waiting t ntfn))
        (fun _ _ h => h)))
    ?_ ?_
  · -- the rest, for related notifications; the executable one is waiting
    refine corres_gen_asm2 (fun hw => ?_)
    obtain ⟨q', hq'⟩ := hw
    obtain ⟨hobj, hbound⟩ := hrel
    -- the abstract notification is waiting on the same queue
    cases hA : n.ntfn_obj with
    | IdleNtfn => rw [hA] at hobj; simp [ntfnObj_relation, hq'] at hobj
    | ActiveNtfn b => rw [hA] at hobj; simp [ntfnObj_relation, hq'] at hobj
    | WaitingNtfn q =>
      rw [hA] at hobj
      simp only [ntfnObj_relation, hq', NTFN.WaitingNtfn.injEq] at hobj
      subst hobj
      -- both sides now reduce to: set the new notification, then make the thread Inactive
      simp only [hq', bind_eq, pure_eq, ret_bind, assertH, assertM, NTFN.ntfnQueue, deleteH,
        erase_map_toPtr, ↓reduceIte]
      cases hqe : q.erase t with
      | nil =>
        simp only [List.map_nil]
        refine corres_guard_imp
          (corres_split
            (H.setNotification_corres ntfn _ _ ⟨by simp [Sel4Lean.Abstract.ntfn_set_obj, ntfnObj_relation], by
              simpa [Sel4Lean.Abstract.ntfn_set_obj] using hbound⟩)
            (fun _ _ _ => H.setThreadState_corres t _ _ rfl)
            (H.set_notification_tcb ntfn _ t) valid_true)
          (fun s h => ⟨h.2.2.2, h.1, h.2.1, h.2.2.1⟩) (fun s h => ⟨h, trivial⟩)
      | cons x xs =>
        simp only [List.map_cons]
        refine corres_guard_imp
          (corres_split
            (H.setNotification_corres ntfn _ _ ⟨by simp [Sel4Lean.Abstract.ntfn_set_obj, ntfnObj_relation, NTFN.set_ntfnQueue], by
              simpa [Sel4Lean.Abstract.ntfn_set_obj] using hbound⟩)
            (fun _ _ _ => H.setThreadState_corres t _ _ rfl)
            (H.set_notification_tcb ntfn _ t) valid_true)
          (fun s h => ⟨h.2.2.2, h.1, h.2.1, h.2.2.1⟩) (fun s h => ⟨h, trivial⟩)
  · -- abstract guard: invs and the blocked thread give everything the parts need
    intro s ⟨hinv, hst⟩
    obtain ⟨hn, ht, ha, hd⟩ := H.invs_blocked s t ntfn hinv hst
    exact ⟨hn, ht, ha, hd, hn⟩
  · intro s ⟨hinv', hst'⟩
    have h1 := H.invs'_blocked s t ntfn hinv' hst'
    exact ⟨h1, h1, hinv', hst'⟩

/-! ## An invariant lemma on the generated code: `cancelSignal_simple` -/

/-- l4v `idle'` (Invariants_H.thy) -/
def idle' (st : ThreadState) : Prop := st = .IdleThreadState
/-- l4v `awaiting_reply'` (Invariants_H.thy) -/
def awaiting_reply' (st : ThreadState) : Prop := st = .BlockedOnReply
/-- l4v `simple'` (Invariants_H.thy:971) -/
def simple' (st : ThreadState) : Prop :=
  st = .Inactive ∨ st = .Running ∨ st = .Restart ∨ idle' st ∨ awaiting_reply' st

/-- l4v `cancelSignal_simple` (IpcCancel_R.thy:71), proved over the **generated** `cancelSignal`:
```
lemma cancelSignal_simple[wp]:
  "⦃⊤⦄ cancelSignal t ntfn ⦃λrv. st_tcb_at' simple' t⦄"
  by (wpsimp simp: cancelSignal_def Let_def wp: setThreadState_st_tcb)
```
Assumes l4v `setThreadState_st_tcb` (TcbAcc_R.thy:3735). Every earlier step only has to carry the
state-independent fact `simple' Inactive`, which `valid_const` (a `@[wp_rule]`) gives for any program. -/
theorem cancelSignal_simple
    (setThreadState_st_tcb : ∀ (P : ThreadState → Prop) st t,
      ⟪fun _ => P st⟫ (setThreadState st t) ⟪fun _ => st_tcb_at' P t⟫)
    (t : PPtr TCB) (ntfn : PPtr Notification) :
    ⟪fun _ => True⟫ (cancelSignal t ntfn) ⟪fun _ => st_tcb_at' simple' t⟫ := by
  unfold cancelSignal
  wpsimp [setThreadState_st_tcb]
  all_goals (try simp [simple'])

end
end Sel4Lean.Refine
