import Sel4Lean.Spec.Gen.Mod.API_Types_RISCV64
import Sel4Lean.Spec.Gen.Mod.API_Types_Universal
import Sel4Lean.Spec.Gen.Mod.Config
import Sel4Lean.Spec.Gen.Mod.Data_WordLib
import Sel4Lean.Spec.Gen.Mod.Kernel_Thread
import Sel4Lean.Spec.Gen.Mod.Kernel_VSpace_RISCV64
import Sel4Lean.Spec.Gen.Mod.Machine_Hardware
import Sel4Lean.Spec.Gen.Mod.Machine_Hardware_RISCV64
import Sel4Lean.Spec.Gen.Mod.Machine_Hardware_RISCV64_HiFive
import Sel4Lean.Spec.Gen.Mod.Machine_RegisterSet_RISCV64
import Sel4Lean.Spec.Gen.Mod.Model_StateData_RISCV64
import Sel4Lean.Spec.Gen.Mod.Object_ObjectType
import Sel4Lean.Spec.Gen.Mod.Object_ObjectType_RISCV64
import Sel4Lean.Spec.Gen.Mod.Object_Structures_RISCV64

#eval IO.println s!"1|{((Sel4Lean.Spec.M.Data_WordLib.wordBits))}"
#eval IO.println s!"2|{((Sel4Lean.Spec.M.Data_WordLib.wordSize))}"
#eval IO.println s!"3|{((Sel4Lean.Spec.M.Data_WordLib.wordRadix))}"
#eval IO.println s!"4|{((Sel4Lean.Spec.M.API_Types_RISCV64.tcbBlockSizeBits))}"
#eval IO.println s!"5|{((Sel4Lean.Spec.M.API_Types_Universal.epSizeBits))}"
#eval IO.println s!"6|{((Sel4Lean.Spec.M.API_Types_Universal.ntfnSizeBits))}"
#eval IO.println s!"7|{((Sel4Lean.Spec.M.API_Types_Universal.cteSizeBits))}"
#eval IO.println s!"8|{((Sel4Lean.Spec.M.Config.minFreeSlots))}"
#eval IO.println s!"9|{((Sel4Lean.Spec.M.Config.minSmallBlocks))}"
#eval IO.println s!"10|{((Sel4Lean.Spec.M.Config.rootCNodeSize))}"
#eval IO.println s!"11|{((Sel4Lean.Spec.M.Config.timeSlice))}"
#eval IO.println s!"12|{((Sel4Lean.Spec.M.Config.numDomains))}"
#eval IO.println s!"13|{((Sel4Lean.Spec.M.Config.numPriorities))}"
#eval IO.println s!"14|{((Sel4Lean.Spec.M.Config.retypeFanOutLimit)).toNat}"
#eval IO.println s!"15|{((Sel4Lean.Spec.M.Config.resetChunkBits))}"
#eval IO.println s!"16|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (0 : Nat)))}"
#eval IO.println s!"17|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (1 : Nat)))}"
#eval IO.println s!"18|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (2 : Nat)))}"
#eval IO.println s!"19|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (3 : Nat)))}"
#eval IO.println s!"20|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (8 : Nat)))}"
#eval IO.println s!"21|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (12 : Nat)))}"
#eval IO.println s!"22|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (31 : Nat)))}"
#eval IO.println s!"23|{((Sel4Lean.Spec.M.Kernel_Thread.invertL1Index (32 : Nat)))}"
#eval IO.println s!"24|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (0 : BitVec 8)))}"
#eval IO.println s!"25|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (1 : BitVec 8)))}"
#eval IO.println s!"26|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (2 : BitVec 8)))}"
#eval IO.println s!"27|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (7 : BitVec 8)))}"
#eval IO.println s!"28|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (255 : BitVec 8)))}"
#eval IO.println s!"29|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (128 : BitVec 8)))}"
#eval IO.println s!"30|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (158 : BitVec 8)))}"
#eval IO.println s!"31|{((Sel4Lean.Spec.M.Kernel_Thread.prioToL1Index (111 : BitVec 8)))}"
#eval IO.println s!"32|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (0 : Nat))).toNat}"
#eval IO.println s!"33|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (1 : Nat))).toNat}"
#eval IO.println s!"34|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (2 : Nat))).toNat}"
#eval IO.println s!"35|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (3 : Nat))).toNat}"
#eval IO.println s!"36|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (8 : Nat))).toNat}"
#eval IO.println s!"37|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (12 : Nat))).toNat}"
#eval IO.println s!"38|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (31 : Nat))).toNat}"
#eval IO.println s!"39|{((Sel4Lean.Spec.M.Kernel_Thread.l1IndexToPrio (32 : Nat))).toNat}"
#eval IO.println s!"40|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ipcBufferSizeBits))}"
#eval IO.println s!"41|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (0 : Nat)))}"
#eval IO.println s!"42|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (1 : Nat)))}"
#eval IO.println s!"43|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (2 : Nat)))}"
#eval IO.println s!"44|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (3 : Nat)))}"
#eval IO.println s!"45|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (8 : Nat)))}"
#eval IO.println s!"46|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (12 : Nat)))}"
#eval IO.println s!"47|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (31 : Nat)))}"
#eval IO.println s!"48|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptBitsLeft (32 : Nat)))}"
#eval IO.println s!"49|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (0 : Nat) (Sel4Lean.Spec.VPtr.VPtr 0))).toNat}"
#eval IO.println s!"50|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (1 : Nat) (Sel4Lean.Spec.VPtr.VPtr 1))).toNat}"
#eval IO.println s!"51|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (2 : Nat) (Sel4Lean.Spec.VPtr.VPtr 2))).toNat}"
#eval IO.println s!"52|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (3 : Nat) (Sel4Lean.Spec.VPtr.VPtr 7))).toNat}"
#eval IO.println s!"53|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (8 : Nat) (Sel4Lean.Spec.VPtr.VPtr 4095))).toNat}"
#eval IO.println s!"54|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (12 : Nat) (Sel4Lean.Spec.VPtr.VPtr 4096))).toNat}"
#eval IO.println s!"55|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (31 : Nat) (Sel4Lean.Spec.VPtr.VPtr 18446744073709551615))).toNat}"
#eval IO.println s!"56|{((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptIndex (32 : Nat) (Sel4Lean.Spec.VPtr.VPtr 9223372036854775808))).toNat}"
#eval IO.println s!"57|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (0 : Nat) (Sel4Lean.Exec.PPtr.mk 0 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 0)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"58|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (1 : Nat) (Sel4Lean.Exec.PPtr.mk 1 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 1)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"59|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (2 : Nat) (Sel4Lean.Exec.PPtr.mk 2 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 2)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"60|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (3 : Nat) (Sel4Lean.Exec.PPtr.mk 7 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 7)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"61|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (8 : Nat) (Sel4Lean.Exec.PPtr.mk 4095 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 4095)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"62|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (12 : Nat) (Sel4Lean.Exec.PPtr.mk 4096 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 4096)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"63|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (31 : Nat) (Sel4Lean.Exec.PPtr.mk 18446744073709551615 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 18446744073709551615)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"64|{(((Sel4Lean.Spec.M.Kernel_VSpace_RISCV64.ptSlotIndex (32 : Nat) (Sel4Lean.Exec.PPtr.mk 9223372036854775808 : Sel4Lean.Exec.PPtr _) (Sel4Lean.Spec.VPtr.VPtr 9223372036854775808)) : Sel4Lean.Exec.PPtr _)).ptr.toNat}"
#eval IO.println s!"65|{((Sel4Lean.Spec.M.Machine_Hardware.pptrBaseOffset)).toNat}"
#eval IO.println s!"66|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 0)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"67|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 1)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"68|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 2)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"69|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 7)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"70|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 4095)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"71|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 4096)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"72|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 18446744073709551615)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"73|{(((Sel4Lean.Spec.M.Machine_Hardware.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 9223372036854775808)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"74|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 0 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"75|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 1 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"76|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 2 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"77|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 7 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"78|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 4095 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"79|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 4096 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"80|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 18446744073709551615 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"81|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 9223372036854775808 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"82|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 0 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"83|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 1 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"84|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 2 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"85|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 7 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"86|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 4095 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"87|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 4096 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"88|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 18446744073709551615 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"89|{((Sel4Lean.Spec.M.Machine_Hardware.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 9223372036854775808 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"90|{((Sel4Lean.Spec.M.Machine_Hardware.pageBits))}"
#eval IO.println s!"91|{((Sel4Lean.Spec.M.Machine_Hardware.pageColourBits))}"
#eval IO.println s!"92|{(((Sel4Lean.Spec.M.Machine_Hardware.nullPointer) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"93|{(if (Sel4Lean.Spec.M.Machine_Hardware.config_HAVE_FPU) then 1 else 0)}"
#eval IO.println s!"94|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 0))).toNat}"
#eval IO.println s!"95|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 1))).toNat}"
#eval IO.println s!"96|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 2))).toNat}"
#eval IO.println s!"97|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 7))).toNat}"
#eval IO.println s!"98|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 4095))).toNat}"
#eval IO.println s!"99|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 4096))).toNat}"
#eval IO.println s!"100|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 18446744073709551615))).toNat}"
#eval IO.println s!"101|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.fromPAddr (Sel4Lean.Spec.PAddr.PAddr 9223372036854775808))).toNat}"
#eval IO.println s!"102|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.paddrBase)).fromPAddr.toNat}"
#eval IO.println s!"103|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pptrBase)).fromVPtr.toNat}"
#eval IO.println s!"104|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pptrTop)).fromVPtr.toNat}"
#eval IO.println s!"105|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.kernelELFPAddrBase)).fromPAddr.toNat}"
#eval IO.println s!"106|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.kernelELFBase)).fromVPtr.toNat}"
#eval IO.println s!"107|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pptrUserTop)).fromVPtr.toNat}"
#eval IO.println s!"108|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 0)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"109|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 1)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"110|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 2)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"111|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 7)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"112|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 4095)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"113|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 4096)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"114|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 18446744073709551615)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"115|{(((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptrFromPAddr (Sel4Lean.Spec.PAddr.PAddr 9223372036854775808)) : Sel4Lean.Exec.PPtr Unit)).ptr.toNat}"
#eval IO.println s!"116|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 0 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"117|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 1 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"118|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 2 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"119|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 7 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"120|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 4095 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"121|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 4096 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"122|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 18446744073709551615 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"123|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromPPtr (Sel4Lean.Exec.PPtr.mk 9223372036854775808 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"124|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 0 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"125|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 1 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"126|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 2 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"127|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 7 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"128|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 4095 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"129|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 4096 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"130|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 18446744073709551615 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"131|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.addrFromKPPtr (Sel4Lean.Exec.PPtr.mk 9223372036854775808 : Sel4Lean.Exec.PPtr Unit))).fromPAddr.toNat}"
#eval IO.println s!"132|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageBits))}"
#eval IO.println s!"133|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptTranslationBits))}"
#eval IO.println s!"134|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pteBits))}"
#eval IO.println s!"135|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.ptBits))}"
#eval IO.println s!"136|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64.pageColourBits))}"
#eval IO.println s!"137|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64_HiFive.physBase)).fromPAddr.toNat}"
#eval IO.println s!"138|{((Sel4Lean.Spec.M.Machine_Hardware_RISCV64_HiFive.pageColourBits))}"
#eval IO.println s!"139|{((Sel4Lean.Spec.M.Machine_RegisterSet_RISCV64.sstatusSPIE)).toNat}"
#eval IO.println s!"140|{((Sel4Lean.Spec.M.Model_StateData_RISCV64.maxPTLevel))}"
#eval IO.println s!"141|{((Sel4Lean.Spec.M.Object_ObjectType.badgeBits))}"
#eval IO.println s!"142|{((Sel4Lean.Spec.M.Object_ObjectType_RISCV64.cteRightsBits))}"
#eval IO.println s!"143|{((Sel4Lean.Spec.M.Object_ObjectType_RISCV64.cteGuardBits))}"
#eval IO.println s!"144|{((Sel4Lean.Spec.M.Object_ObjectType_RISCV64.asidPoolBits))}"
#eval IO.println s!"145|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.minUntypedSizeBits))}"
#eval IO.println s!"146|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.maxUntypedSizeBits))}"
#eval IO.println s!"147|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBits))}"
#eval IO.println s!"148|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidLowBits))}"
#eval IO.println s!"149|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidBits))}"
#eval IO.println s!"150|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 0))).fromASID.toNat}"
#eval IO.println s!"151|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 1))).fromASID.toNat}"
#eval IO.println s!"152|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 2))).fromASID.toNat}"
#eval IO.println s!"153|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 7))).fromASID.toNat}"
#eval IO.println s!"154|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 4095))).fromASID.toNat}"
#eval IO.println s!"155|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 4096))).fromASID.toNat}"
#eval IO.println s!"156|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 18446744073709551615))).fromASID.toNat}"
#eval IO.println s!"157|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.asidHighBitsOf (Sel4Lean.Spec.ASID.ASID 9223372036854775808))).fromASID.toNat}"
#eval IO.println s!"158|{((Sel4Lean.Spec.M.Object_Structures_RISCV64.timeArgLen))}"
