"""hs2lean full mode (W2): translate at spec scale, stub what can't be translated, report coverage.

    full.py types ROOT_SRC_DIR FILE [FILE ...]  > Types.lean   (+ coverage report on stderr)

`types`: translate every data/newtype/type declaration in FILEs, follow every type name they mention to
its declaration anywhere under ROOT_SRC_DIR (RISCV64 variants only), translate those too, and emit
`opaque` stubs only for names that can't be resolved or translated. Output is in dependency order.
"""
import os
import re
import sys
from hs2lean import (Translator, DataInfo, Unsupported, parse_file, top_decls, kids, TYPE)

ARCH = "RISCV64"
# names defined by hand-written Lean (Spec/PSpaceStorable.lean): never emitted or stubbed by hs2lean
PROVIDED = {"makeObject", "injectKO", "projectKO", "loadObject", "updateObject", "objBits", "alignCheck",
            "sizeCheck", "alignError", "typeError", "doMachineOp", "funArray", "funPartialArray"}
# Machine-interface modules: the Haskell bodies are the simulator's (FFI/IO). l4v's Isabelle treats machine
# operations as opaque with assumed properties (MachineOps.thy), so these functions are stubbed by design.
MACHINE_INTERFACE = ("SEL4/Machine/Hardware",)

# Haskell classes kept as Lean instance arguments (others, e.g. Bits/Num/MonadFail, are dropped)
KEPT_CLASSES = {"PSpaceStorable": ["PSpaceStorable"], "MonadFail": ["Monad", "MonadFailH"],
                "Monad": ["Monad"], "Ord": ["OrdH"], "Eq": ["DecidableEq"], "Bits": ["BitsH"],
                "FiniteBits": ["BitsH"], "Bounded": ["BoundedH"], "Integral": ["IntegralH"],
                "Num": ["IntegralH"], "Enum": ["IntegralH"], "Ix": ["IntegralH"]}
KEPT_CLASSES["Integral"] = ["IntegralH", "OrdH"]   # Haskell: class (Real a, Enum a) => Integral a; Real ⊇ Ord
HEADER = """/-
  GENERATED by tools/hs2lean/full.py (types closure) from l4v's Haskell spec, RISCV64.
  Do not edit by hand; regenerate with env/remote/hs2lean.sh.
-/
"""
OTHER_ARCHES = {"ARM", "ARM_HYP", "X64", "AARCH64"}

# Haskell library types -> Lean (l4v's Isabelle model makes maps and arrays functions)
LIB_TYPES = {"Word8": "BitVec 8", "Word16": "BitVec 16", "Word32": "BitVec 32", "Word64": "BitVec 64",
             # Haskell Int -> Nat, as l4v's translator maps it to nat
             "Int": "Nat", "Integer": "Int", "Bool": "Bool", "Word": "Word", "Char": "Char",
             "String": "String", "Maybe": "Option", "Either": "Except",
             # monads (see notes/w2-translation.md): l4v's Isabelle model where it exists, Lean core otherwise
             "State": "Sel4Lean.NondetM", "StateT": "StateT", "ReaderT": "ReaderT", "ExceptT": "ExceptT",
             "IO": "IO", "Ptr": "PtrH"}
TYPE.update(LIB_TYPES)


def arch_ok(path):
    stem = os.path.splitext(os.path.basename(path))[0]
    parts = set(path.split(os.sep))
    return stem not in OTHER_ARCHES and not (parts & OTHER_ARCHES)


def index_decls(root):
    """name -> (src, node, path) for data/newtype/type declarations (and signatures, under 'sig:')."""
    idx = {}
    for d, _, fs in os.walk(root):
        for f in sorted(fs):
            if not f.endswith((".hs", ".lhs")):
                continue
            path = os.path.join(d, f)
            if not arch_ok(path):
                continue
            try:
                src, root_node = parse_file(path)
            except Exception:
                continue
            decls = next((c for c in root_node.children if c.type == "declarations"), None)
            if decls is None:
                continue
            for n in kids(decls):
                if n.type in ("data_type", "newtype", "type_synonym", "signature"):
                    name_node = n.child_by_field_name("name")
                    if name_node is None:
                        continue
                    name = src[name_node.start_byte:name_node.end_byte].decode()
                    key = ("sig:" + name) if n.type == "signature" else name
                    idx.setdefault(key, []).append((src, n, path))
    # A name may be declared in several modules: `type PAddr = Arch.PAddr` (Hardware.lhs) re-exports
    # `type PAddr = Platform.PAddr` (RISCV64) which re-exports the platform's `newtype PAddr`.
    # Prefer a real declaration over a pure re-export.
    def reexport(entry):
        src, n, _ = entry
        if n.type != "type_synonym":
            return False
        name = src[n.child_by_field_name("name").start_byte:n.child_by_field_name("name").end_byte].decode()
        rhs = kids(n)[-1]
        return rhs.type == "qualified" and src[rhs.start_byte:rhs.end_byte].decode().split(".")[-1] == name
    best = {k: next((e for e in v if not reexport(e)), v[0]) for k, v in idx.items()}
    # type names declared per file (for Haskell's same-file scoping of arch names)
    per_file = {}
    for k, v in idx.items():
        if not k.startswith("sig:"):
            for e in v:
                per_file.setdefault(e[2], set()).add(k)
    best["__file_types__"] = per_file
    # every RISCV64 file declaring X in any form (incl. re-exports), for arch scoping
    best["__arch_decl_files__"] = {k: {e[2] for e in v if ARCH in e[2]} for k, v in idx.items()
                                   if not k.startswith("sig:")}
    # arch-specific declarations, for `Arch.X` inside a generic type also named X (e.g. newtype IRQ = IRQ Arch.IRQ)
    for k, v in idx.items():
        arch = [e for e in v if ARCH in e[2] and not reexport(e)]
        if arch:
            best[f"{ARCH}.{k}"] = arch[0]
    return best


_IMPORT_CACHE = {}


def module_of(path, root):
    """`SEL4/Model/StateData/RISCV64.hs` -> `SEL4.Model.StateData.RISCV64`."""
    return os.path.splitext(os.path.relpath(path, root))[0].replace(os.sep, ".")


def unqualified_imports(path):
    """Modules a file imports without `qualified` (the spec's `TARGET` placeholder is the architecture)."""
    if path not in _IMPORT_CACHE:
        src, rn = parse_file(path)
        mods = set()
        imps = next((c for c in rn.children if c.type == "imports"), None)
        for imp in kids(imps) if imps is not None else []:
            if any(c.type == "qualified" for c in imp.children):
                continue
            m = imp.child_by_field_name("module")
            if m is not None:
                mods.add(src[m.start_byte:m.end_byte].decode().replace("TARGET", ARCH))
        _IMPORT_CACHE[path] = mods
    return _IMPORT_CACHE[path]


_MODULE_PATHS = {}
_DEFS_CACHE = {}


def module_paths(root):
    """Haskell module name -> file, for every RISCV64-relevant module."""
    if root not in _MODULE_PATHS:
        m = {}
        for top in ("SEL4", "Data"):
            for d, _, fs in os.walk(os.path.join(root, top)):
                for f in fs:
                    pth = os.path.join(d, f)
                    if f.endswith((".hs", ".lhs")) and arch_ok(pth):
                        m[module_of(pth, root)] = pth
        _MODULE_PATHS[root] = m
    return _MODULE_PATHS[root]


def direct_imports(path):
    """Modules imported without {-# SOURCE #-} (those break cycles and stay stubs), TARGET = RISCV64."""
    src, rn = parse_file(path)
    out = []
    imps = next((c for c in rn.children if c.type == "imports"), None)
    for imp in kids(imps) if imps is not None else []:
        if "SOURCE" in src[imp.start_byte:imp.end_byte].decode():
            continue
        m = imp.child_by_field_name("module")
        if m is not None:
            out.append(src[m.start_byte:m.end_byte].decode().replace("TARGET", ARCH))
    return out


def import_closure(path, root):
    """Transitive non-SOURCE imports, in breadth-first order (direct imports first)."""
    mp = module_paths(root)
    seen, order, queue = set(), [], [m for m in direct_imports(path)]
    while queue:
        m = queue.pop(0)
        if m in seen or m not in mp:
            continue
        seen.add(m)
        order.append(m)
        queue.extend(direct_imports(mp[m]))
    return order


GEN_DIR = None   # where generated module files are read back from (set by --gen-dir)


def module_defs(path, root=None):
    """Names a module's generated Lean file actually defines in its namespace (defs, partial defs, stubs,
    aliases). Read from the generated file: a Haskell function that could not be translated or stubbed has no
    Lean definition. Falls back to the Haskell source when no generated file is available."""
    key = (path, GEN_DIR)
    if key not in _DEFS_CACHE:
        names = None
        if GEN_DIR and root:
            lf = os.path.join(GEN_DIR, lean_module(module_of(path, root)) + ".lean")
            if os.path.exists(lf):
                names = set(re.findall(r"^(?:partial def|def|opaque|abbrev) «?([^\s»]+)»?", open(lf).read(), re.M))
        if names is None:
            src, rn = parse_file(path)
            names = {n for n, ns in top_decls(src, rn) if any(d.type in ("function", "bind") for d in ns)}
        _DEFS_CACHE[key] = names
    return _DEFS_CACHE[key]


def dependency_order(root, files):
    """Files ordered so that every module comes after the modules it imports (non-SOURCE)."""
    mp = module_paths(root)
    inv = {v: k for k, v in mp.items()}
    order, done = [], set()

    def visit(f, path=()):
        if f in done or f in path:
            return
        for m in direct_imports(f):
            if m in mp:
                visit(mp[m], path + (f,))
        done.add(f)
        order.append(f)
    for f in files:
        visit(f)
    return [f for f in order if f in set(files)]


def lean_module(hs_module):
    """SEL4.Object.TCB.RISCV64 -> Object_TCB_RISCV64 (the generated Lean module/namespace suffix)."""
    parts = hs_module.split(".")
    if parts[0] == "SEL4":
        parts = parts[1:]
    return "_".join(parts)


def arch_scope(path, root, idx, candidates):
    """Arch types X that an unqualified `X` means in this file (Haskell scoping): those declared in this
    file or in a module it imports unqualified, counting re-exports (`type IRQ = Platform.IRQ`)."""
    visible = unqualified_imports(path) | {module_of(path, root)}
    files = idx.get("__arch_decl_files__", {})
    return {x for x in candidates
            if f"{ARCH}.{x}" in idx and ({module_of(f, root) for f in files.get(x, ())} & visible)}


class FullTranslator(Translator):
    """Translator with type variables, contexts, qualified library types, newtypes, synonyms."""

    def __init__(self, src, data):
        super().__init__(src, data)
        self.tyvars = []
        self.current_ctors = set()
        self.current_name = None
        self.arch_names = set()      # types X with a translated RISCV64.X
        self.arch_names_all = set()  # same, regardless of module (for explicit `Arch.X`)
        self.file_types = set()      # type names declared in the file being translated
        self.arch_in_scope = set()   # arch types an unqualified name refers to in this file
        self.in_arch_module = False  # in a RISCV64 module, unqualified X means RISCV64.X
        self.arch_calls = set()      # `Arch.f` references seen while translating
        self.constraints = []        # kept class constraints of the current signature
        self.hk = set()              # higher-kinded type variables (`m` in `m a`)
        self.discard_stmts = True    # `let _ ← e` for non-final do statements

    def ty(self, n):
        t = n.type
        if t == "name" and self.text(n) in self.current_ctors:
            return f"Sel4Lean.Spec.{self.text(n)}"   # a constructor of this type has the same name
        if t == "name" and self.text(n) in self.arch_in_scope:
            # Haskell scoping: unqualified X means the arch X when declared in this file or in a module
            # imported unqualified; otherwise arch types are reached through a qualifier (Arch.X, …)
            return f"{ARCH}.{self.text(n)}"
        if t == "variable":
            # Haskell lets a type variable share a term parameter's name (`wordSizeCase :: a -> a -> a` with
            # `wordSizeCase a b`); Lean doesn't, so type variables get a prefix
            v = "t_" + self.text(n)
            if v not in self.tyvars:
                self.tyvars.append(v)
            return v
        if t == "context":
            # keep constraints of KEPT_CLASSES as instance binders, e.g. [PSpaceStorable a]
            c = n.child_by_field_name("context")
            for cl in ([c] if c is not None and c.type == "apply" else kids(c) if c is not None else []):
                if cl.type == "apply":
                    head = self.text(cl.child_by_field_name("constructor"))
                    arg = self.text(cl.child_by_field_name("argument"))
                    for lc in KEPT_CLASSES.get(head, []):
                        if (lc, "t_" + arg) not in self.constraints:
                            self.constraints.append((lc, "t_" + arg))
            return self.ty(n.child_by_field_name("type"))
        if t in ("field", "strict_field", "lazy_field"):
            inner = n.child_by_field_name("type") or kids(n)[-1]
            return self.ty(inner)
        if t == "qualified":
            # `Arch.IRQ` etc.: the spec imports the RISCV64 module qualified; resolve by the base name,
            # or to the arch declaration if the base name is the type being defined (a wrapper)
            q, base = self.text(n).rsplit(".", 1)
            if base == self.current_name or (q.startswith("Arch") and base in self.arch_names_all):
                return f"{ARCH}.{base}"
            return TYPE.get(base, base)
        if t == "apply":
            # collect head and args to handle library types with arity
            args, m = [], n
            while m.type == "apply":
                args.append(m.child_by_field_name("argument"))
                m = m.child_by_field_name("constructor")
            args.reverse()
            head = self.text(m)
            if m.type == "variable":   # `m a`: a type-constructor variable (monad)
                self.hk.add("t_" + head)
            if head in ("Data.Map.Map", "Map") and len(args) == 2:
                return f"({self.ty_atom(args[0])} → Option {self.ty_atom(args[1])})"
            if head in ("Set", "Data.Set.Set") and len(args) == 1:
                return f"({self.ty_atom(args[0])} → Prop)"   # Isabelle sets are predicates
            if head == "Array" and len(args) == 2:
                return f"({self.ty_atom(args[0])} → {self.ty_atom(args[1])})"
            if m.type == "qualified" and head not in ("Data.Map.Map",):
                # resolve Arch.X etc. by base name (see `qualified` above)
                pass
        return super().ty(n)

    def e(self, n, ind):
        # `Arch.f` names the RISCV64 implementation (generic modules dispatch with `f = Arch.f`)
        if n.type == "qualified":
            txt = self.text(n)
            q, base = txt.rsplit(".", 1)
            if q in ("Data.Map", "Map"):
                return f"MapH.{base}"
            if q in ("Data.Set", "Set"):
                return f"SetH.{base}"
            if q.startswith("Arch") and base[:1].islower():
                self.arch_calls.add(base)
                return f"{ARCH}.{base}"
        return super().e(n, ind)

    def ctor(self, name):
        if self.in_arch_module and name in self.data.arch_ctor_type:
            return f"{self.data.arch_ctor_type[name]}.{name}"
        return super().ctor(name)

    def emit_function(self, name, nodes, sig_override=None):
        self.constraints, self.hk, self.tyvars = [], set(), []
        body = [d for d in nodes if d.type != "signature"]
        self.bound = set().union(*(bound_names(self, d) for d in body)) | self.wildcard_fields(body)
        sig = next((d for d in nodes if d.type == "signature"), None)
        if sig is not None:
            self.ty(sig.child_by_field_name("type"))   # records constraints and higher-kinded vars
        text = super().emit_function(name, nodes, sig_override=sig_override)
        plain = [v for v in self.tyvars if v not in self.hk]
        if self.constraints or self.hk or plain:
            inst = " ".join([f"{{{v} : Type → Type}}" for v in sorted(self.hk)]
                            + [f"{{{v} : Type}} [Inhabited {v}]" for v in plain]
                            + [f"[{c} {v}]" for c, v in self.constraints])
            text = text.replace(f"\ndef {self.ident(name)} ", f"\ndef {self.ident(name)} {inst} ", 1)
        return text

    def wildcard_fields(self, nodes):
        """Field names brought into scope by `C {..}` patterns."""
        out, stack = set(), list(nodes)
        while stack:
            m = stack.pop()
            if m.type == "record" and ".." in self.text(m):
                c = m.child_by_field_name("constructor")
                cname = self.text(c).split(".")[-1] if c is not None else None
                tname = self.data.ctor_type.get(cname) if cname else None
                if tname:   # only the fields of this constructor
                    for cn, fs, _ in self.data.types[tname]["ctors"]:
                        if cn == cname:
                            out |= {f for f, _ in (fs or [])}
            if m.type == "field_pattern" and len(kids(m)) == 1:
                # NamedFieldPuns: `C { f }` (only the field name) binds f; `C { f = p }` binds p instead
                out.add(self.text(kids(m)[0]).split(".")[-1])
            stack.extend(m.named_children)
        return out

    def backtick_fn(self, op):
        if "." in op:
            q, base = op.rsplit(".", 1)
            if q.startswith("Arch"):
                self.arch_calls.add(base)
                return f"{ARCH}.{base}"
            if q in ("Data.Map", "Map"):
                return f"MapH.{base}"
        return super().backtick_fn(op)

    def type_names(self, n):
        """Type constructor names mentioned under n (not in `deriving` clauses; qualifiers dropped)."""
        out, stack = set(), [n]
        while stack:
            m = stack.pop()
            if m.type == "deriving":
                continue
            if m.type == "name":
                nm = self.text(m)
                out.add(f"{ARCH}.{nm}" if nm in self.arch_in_scope else nm)
            elif m.type == "qualified":
                base = self.text(m).split(".")[-1]
                out.add(f"{ARCH}.{base}" if base == self.current_name else base)
                continue
            stack.extend(m.named_children)
        return out

    def params(self, node):
        tp = node.child_by_field_name("patterns") or next((c for c in kids(node) if c.type == "type_params"), None)
        return ["t_" + self.text(v) for v in kids(tp)] if tp is not None else []   # same prefix as in ty()

    def emit_synonym(self, name, node):
        body = [c for c in kids(node) if c.type != "name" or self.text(c) != name]
        ps = self.params(node)
        rhs = node.child_by_field_name("type") or body[-1]
        binders = "".join(f" ({p} : Type)" for p in ps)
        return f"/-- Haskell `type {name}` -/\nabbrev {name}{binders} := {self.ty(rhs)}"

    def emit_newtype(self, name, node):
        ps = self.params(node)
        binders = "".join(f" ({p} : Type)" for p in ps)
        nc = next(c for c in kids(node) if c.type == "newtype_constructor")
        cname = self.text(next(c for c in kids(nc) if c.type == "constructor"))
        rec = next((c for c in kids(nc) if c.type == "record"), None)
        if rec is not None:
            f = next(c for c in kids(rec) if c.type == "field")
            fname = self.text(f.child_by_field_name("name"))
            fty = self.ty(f.child_by_field_name("type"))
        else:
            fname = "val"
            fty = self.ty(next(c for c in kids(nc) if c.type != "constructor"))
        d = node.child_by_field_name("deriving") or next((c for c in kids(node) if c.type == "deriving"), None)
        dtext = self.text(d) if d is not None else ""
        eq = "Eq" in dtext and "→" not in fty
        derives = "deriving Inhabited, DecidableEq" if eq else "deriving Inhabited"
        inst = []
        if not ps and (fty == "Word" or fty.startswith("BitVec")):
            # Haskell `deriving (Num, Ord, Bits, …)` on a word newtype: lift through the field
            mk = lambda e: f"⟨{e}⟩"
            if "Num" in dtext or "Integral" in dtext:
                inst += [f"instance {{n : Nat}} : OfNat {name} n := ⟨⟨OfNat.ofNat n⟩⟩",
                         f"instance : Add {name} := ⟨fun a b => {mk(f'a.{fname} + b.{fname}')}⟩",
                         f"instance : Sub {name} := ⟨fun a b => {mk(f'a.{fname} - b.{fname}')}⟩",
                         f"instance : Mul {name} := ⟨fun a b => {mk(f'a.{fname} * b.{fname}')}⟩",
                         ]
            if "Ord" in dtext:
                inst += [f"instance : LE {name} := ⟨fun a b => a.{fname} ≤ b.{fname}⟩",
                         f"instance : LT {name} := ⟨fun a b => a.{fname} < b.{fname}⟩",
                         f"instance (a b : {name}) : Decidable (a ≤ b) := inferInstanceAs (Decidable (a.{fname} ≤ b.{fname}))",
                         f"instance (a b : {name}) : Decidable (a < b) := inferInstanceAs (Decidable (a.{fname} < b.{fname}))"]
            if "Bounded" in dtext:
                inst += [f"instance : BoundedH {name} := ⟨⟨BoundedH.minB⟩, ⟨BoundedH.maxB⟩⟩"]
            if "Bits" in dtext:
                inst += [f"instance : BitsH {name} := ⟨fun a i => BitsH.testBitB a.{fname} i, "
                         f"fun a => ⟨BitsH.complementB a.{fname}⟩, fun a => BitsH.finiteBitSizeB a.{fname}⟩"]
                inst += [f"instance : AndOp {name} := ⟨fun a b => {mk(f'a.{fname} &&& b.{fname}')}⟩",
                         f"instance : OrOp {name} := ⟨fun a b => {mk(f'a.{fname} ||| b.{fname}')}⟩",
                         f"instance : HShiftLeft {name} Nat {name} := ⟨fun a k => {mk(f'a.{fname} <<< k')}⟩",
                         f"instance : HShiftRight {name} Nat {name} := ⟨fun a k => {mk(f'a.{fname} >>> k')}⟩"]
        if not ps and not (fty == "Word" or fty.startswith("BitVec")) and "→" not in fty:
            # lifted through a non-word field (e.g. generic `newtype IRQ = IRQ Arch.IRQ`): the field's own
            # instances may be hand-written Haskell instances, emitted at the end, so defer these
            if "Bounded" in dtext:
                self.data.deferred.append(f"instance : BoundedH {name} := ⟨⟨BoundedH.minB⟩, ⟨BoundedH.maxB⟩⟩")
            if any(k in dtext for k in ("Enum", "Num", "Integral")):
                self.data.deferred.append(f"instance : IntegralH {name} := ⟨fun a => IntegralH.toInt a.{fname}, "
                                          f"fun i => ⟨IntegralH.ofInt i⟩⟩")
            if "Ord" in dtext:
                self.data.deferred += [f"instance [LT {fty}] : LT {name} := ⟨fun a b => a.{fname} < b.{fname}⟩",
                                       f"instance [LE {fty}] : LE {name} := ⟨fun a b => a.{fname} ≤ b.{fname}⟩"]
        # IntegralH (fromIntegral/fromEnum) lifted through the field, for Enum/Num/Integral newtypes whose
        # field is a word or another such newtype
        if not ps and any(k in dtext for k in ("Enum", "Num", "Integral")) and (
                fty == "Word" or fty.startswith("BitVec") or fty in self.data.integral):
            inst.append(f"instance : IntegralH {name} := ⟨fun a => IntegralH.toInt a.{fname}, "
                        f"fun i => ⟨IntegralH.ofInt i⟩⟩")
            self.data.integral.add(name)
        self.data.types[name] = {"ctors": [(cname, [(fname, None)], [])], "single": True}
        if name.startswith(ARCH + "."):
            self.data.arch_ctor_type[cname] = name   # arch modules resolve `IRQ` to RISCV64.IRQ.IRQ
            self.data.ctor_type.setdefault(cname, name)
        else:
            self.data.ctor_type[cname] = name
        if rec is not None:   # only real record fields are selectors (the synthetic `val` is not)
            self.data.field_type[fname] = name
        # name the Lean constructor like the Haskell one, so `CPtr x` patterns and expressions work
        return (f"/-- Haskell `newtype {name} = {cname} …` -/\n"
                f"structure {name}{binders} where\n  {cname} ::\n  {fname} : {fty}\n  {derives}\n"
                + "".join(i + "\n" for i in inst))


def cmd_types(root, files, emit=True):
    idx = index_decls(root)
    data = DataInfo()
    want = []
    for path in files:
        src, rn = parse_file(path)
        for name, nodes in top_decls(src, rn):
            if any(n.type in ("data_type", "newtype", "type_synonym") for n in nodes):
                want.append(name)
    # closure over referenced type names
    order, seen, stubs, failed, out = [], set(), {}, {}, {}
    deps = {}
    # types X declared both generically and for RISCV64 (Register, KernelState, IRQ, …): inside RISCV64
    # files, unqualified X means RISCV64.X
    dupes = {k[len(ARCH) + 1:] for k in idx
             if not k.startswith("__") and k.startswith(ARCH + ".") and not k.startswith(ARCH + ".sig:")
             and k[len(ARCH) + 1:] in idx and idx[k] is not idx[k[len(ARCH) + 1:]]}

    deferred = []   # newtype instances lifted through non-word fields (need the hand instances first)

    def visit(name):
        if name in seen or name in LIB_TYPES or name in ("PPtr", "Type", "Array", "Map", "Set"):
            return
        if name == "MachineMonad":
            seen.add(name)
            deps[name] = set()
            out[name] = ("/-- Haskell `type MachineMonad = ReaderT MachineData IO` (simulator), modelled as l4v's\n"
                         "Isabelle `machine_monad = (machine_state, 'a) nondet_monad`; the machine state is opaque\n"
                         "for now (TODO(W3)) -/\n"
                         "opaque MachineStateImpl : NonemptyType\n"
                         "def MachineState : Type := MachineStateImpl.type\n"
                         "instance : Nonempty MachineState := MachineStateImpl.property\n"
                         "abbrev MachineMonad := Sel4Lean.NondetM MachineState", "SEL4/Machine/Hardware/RISCV64.hs")
            order.append(name)
            return
        if name == "Kernel":
            seen.add(name)
            visit("KernelState")
            deps[name] = {"KernelState"}
            out[name] = ("/-- Haskell `type Kernel = StateT KernelState MachineMonad`, modelled as l4v's Isabelle\n"
                         "`kernel = (kernel_state, 'a) nondet_monad` -/\n"
                         "abbrev Kernel := Sel4Lean.NondetM KernelState", "SEL4/Model/StateData.lhs")
            order.append(name)
            return
        seen.add(name)
        if name not in idx:
            stubs[name] = "no declaration found"
            return
        src, node, path = idx[name]
        tr = FullTranslator(src, data)
        tr.current_name = name.split(".")[-1] if not name.startswith(ARCH + ".") else None
        if ARCH in path:
            tr.in_arch_module, tr.arch_names = True, dupes - {name.split(".")[-1]}
            tr.file_types = idx["__file_types__"].get(path, set())
        tr.arch_in_scope = arch_scope(path, root, idx, dupes - {name.split(".")[-1]})
        refs = tr.type_names(node) - {name, name.split(".")[-1]}
        deps[name] = refs
        for r in sorted(refs):
            visit(r)
        try:
            if node.type == "data_type" and node.child_by_field_name("constructors") is None:
                raise Unsupported("data type without constructors (opaque in Haskell)")
            if node.type == "data_type":
                tr.collect_data(name, node)
                tr.current_ctors = {c for c, _, _ in data.types[name]["ctors"]}
                text = tr.emit_data(name, node)
                ps = tr.params(node)
                if ps:
                    # parameterised: binders on the inductive; selectors/setters get implicit binders and
                    # the applied type `T a` (constructor fields already say `T a`, from the source)
                    binders = "".join(f" ({p} : Type)" for p in ps)
                    applied = f"({name} {' '.join(ps)})"
                    imp = "".join(f" {{{p} : Type}}" for p in ps)
                    text = text.replace(f"inductive {name} where", f"inductive {name}{binders} where")
                    nullary = next((c for c, f, a in data.types[name]["ctors"] if not f and not a), None)
                    inh = (f"\ninstance{imp} : Inhabited {applied} := ⟨.{nullary}⟩\n" if nullary else "")
                    text = text.replace("deriving Inhabited, DecidableEq", inh)
                    lines = []
                    for line in text.split("\n"):
                        if line.startswith(f"def {name}."):
                            head, rest = line.split(" ", 2)[1], line.split(" ", 2)[2]
                            rest = re.sub(rf"(?<![\w.]){re.escape(name)}(?![\w.])(?! [a-z])", applied, rest)
                            line = f"def {head}{imp} {rest}"
                        lines.append(line)
                    text = "\n".join(lines)
            elif node.type == "newtype":
                text = tr.emit_newtype(name, node)
            else:
                text = tr.emit_synonym(name, node)
            out[name] = (text, os.path.relpath(path, root))
            order.append(name)
        except Unsupported as ex:
            failed[name] = str(ex)
            data.types.pop(name, None)

    for n in want:
        visit(n)
    # strongly connected components (Tarjan) over translated types: pointer cycles need `mutual`
    names = [n for n in order]
    graph = {n: [d for d in deps.get(n, ()) if d in out] for n in names}
    index, low, stack, on, sccs, counter = {}, {}, [], set(), [], [0]

    def strong(v):
        index[v] = low[v] = counter[0]; counter[0] += 1
        stack.append(v); on.add(v)
        for w in graph[v]:
            if w not in index:
                strong(w); low[v] = min(low[v], low[w])
            elif w in on:
                low[v] = min(low[v], index[w])
        if low[v] == index[v]:
            comp = []
            while True:
                w = stack.pop(); on.discard(w); comp.append(w)
                if w == v:
                    break
            sccs.append(comp)
    sys.setrecursionlimit(10000)
    for v in names:
        if v not in index:
            strong(v)
    # types containing function fields (directly or via other types) cannot derive DecidableEq
    has_fn = {n for n in names if "→" in out[n][0].split("deriving")[0].split("/-- Haskell selector")[0]}
    changed = True
    while changed:
        changed = False
        for n in names:
            if n not in has_fn and any(d in has_fn for d in graph[n]):
                has_fn.add(n); changed = True

    def split(n):
        text = out[n][0]
        if n in has_fn:
            text = text.replace("deriving Inhabited, DecidableEq", "deriving Inhabited")
        lines = text.split("\n")
        i = next((k for k, l in enumerate(lines) if l.strip().startswith("deriving ")), None)
        if i is None:
            return text, None, ""
        return "\n".join(lines[:i]), lines[i].strip()[len("deriving "):], "\n".join(lines[i + 1:])

    if not emit:
        return idx, data, {n[len(ARCH) + 1:] for n in order if n.startswith(ARCH + ".")}
    print(HEADER)
    print("import Sel4Lean.Exec.Prelude\nimport Sel4Lean.Spec.HsPrelude\n\nnamespace Sel4Lean.Spec\nopen Sel4Lean.Exec (Word PPtr PtrH)\nnoncomputable section\n")
    print("/-! ## Stubs: types that could not be resolved or translated (hs2lean full) -/\n")
    for n in sorted(set(stubs) | set(failed)):
        why = stubs.get(n) or failed.get(n)
        print(f"-- {n}: {why}")
        print(f"opaque {n}Impl : NonemptyType\ndef {n} : Type := {n}Impl.type\n"
              f"instance : Nonempty {n} := {n}Impl.property\n"
              f"noncomputable instance : Inhabited {n} := ⟨Classical.choice {n}Impl.property⟩\n")
    print("/-! ## Translated -/\n")
    for comp in sccs:   # Tarjan emits components in dependency order
        cyclic = len(comp) > 1 or comp[0] in graph[comp[0]]
        if not cyclic:
            n = comp[0]
            print(f"-- from {out[n][1]}")
            dec, der, post = split(n)
            if n in has_fn and der is not None:
                # contains functions (arrays, maps): classical equality, as in HOL
                print(dec + "\n  deriving Inhabited\n" + post)
                print(f"noncomputable instance : DecidableEq {n} := Classical.typeDecidableEq {n}")
            else:
                print(out[n][0])
            print()
            continue
        comp = sorted(comp, key=names.index)
        parts = {n: split(n) for n in comp}
        print(f"-- pointer cycle: {', '.join(comp)}")
        print("mutual")
        for n in comp:
            print(f"-- from {out[n][1]}")
            print(parts[n][0])
        print("end\n")
        # instances one by one (an inductive with a nullary constructor first). DecidableEq is derived per
        # mutual group in Lean and some members contain functions, so the group gets classical equality,
        # like HOL's (proofs never need to compute it)
        for n in sorted(comp, key=lambda n: 0 if "inductive" in parts[n][0] else 1):
            for cls in (parts[n][1] or "").split(","):
                cls = cls.strip()
                if cls == "DecidableEq":
                    continue
                if cls:
                    print(f"deriving instance {cls} for {n}")
        for n in comp:
            print(f"noncomputable instance : DecidableEq {n} := Classical.typeDecidableEq {n}")
        for n in comp:
            if parts[n][2].strip():
                print(parts[n][2])
        print()
    # hand-written Haskell `instance Bounded T` / `instance Enum T` (others are derived, above)
    print("/-! ## Hand-written Haskell instances (Bounded, Enum) -/\n")
    chosen_platform = os.path.basename(idx[f"{ARCH}.IRQ"][2]) if f"{ARCH}.IRQ" in idx else None
    for path in files:
        if "/Hardware/RISCV64/" in path and chosen_platform and os.path.basename(path) != chosen_platform:
            continue   # another RISCV64 platform
        src, rn = parse_file(path)
        decls = next((c for c in rn.children if c.type == "declarations"), None)
        if decls is None:
            continue
        tr = FullTranslator(src, data)
        if ARCH in path:
            tr.in_arch_module, tr.arch_names = True, dupes
            tr.file_types = idx["__file_types__"].get(path, set())
        tr.arch_in_scope = arch_scope(path, root, idx, dupes)
        for inst in kids(decls):
            if inst.type != "instance":
                continue
            cls = tr.text(inst.child_by_field_name("name"))
            tps = inst.child_by_field_name("patterns")
            if cls not in ("Bounded", "Enum") or tps is None or len(kids(tps)) != 1 or kids(tps)[0].type != "name":
                continue
            tn = tr.ty(kids(tps)[0])
            if tn.split(".")[-1] not in out and tn not in out:
                continue
            body = inst.child_by_field_name("declarations")
            methods = {}
            for d in kids(body) if body is not None else []:
                nm = d.child_by_field_name("name")
                if nm is not None:
                    methods.setdefault(tr.text(nm), []).append(d)
            try:
                if cls == "Bounded":
                    print(f"-- from {os.path.relpath(path, root)}")
                    print(f"instance : BoundedH {tn} := ⟨{tr.rhs(methods['minBound'][0], 2)}, "
                          f"{tr.rhs(methods['maxBound'][0], 2)}⟩\n")
                else:
                    # a method calling `toEnum`/`fromEnum` without changing type refers to this very
                    # instance (InvocationLabel's toEnum does: an infinite loop in Haskell for that branch);
                    # Lean cannot refer to the instance inside its own definition
                    def self_ref(e):
                        txt = tr.text(e)
                        return re.search(r"then toEnum n\b|= toEnum n$", txt, re.M) is not None
                    if any(self_ref(e) for e in methods.get("toEnum", [])):
                        raise Unsupported("toEnum refers to itself (non-terminating in Haskell)")
                    print(f"-- from {os.path.relpath(path, root)}")
                    for m, (dom, cod) in (("fromEnum", (tn, "Nat")), ("toEnum", ("Nat", tn))):
                        eqs = methods[m]
                        tr.bound = set().union(*(bound_names(tr, e) for e in eqs))
                        ps0 = eqs[0].child_by_field_name("patterns")
                        if ps0 is None:   # point-free
                            print(f"def {m}H_{tn.replace('.', '_')} : {dom} → {cod} :=\n  {tr.rhs(eqs[0], 2)}")
                            continue
                        # helper outside the type's namespace: inside `def T.f`, a constructor named like a type
                        # (ObjectType.APIObjectType) would capture type annotations
                        print(f"def {m}H_{tn.replace('.', '_')} : {dom} → {cod} := fun x0 =>\n  match x0 with")
                        for e in eqs:
                            p0 = kids(e.child_by_field_name("patterns"))[0]
                            lines = []
                            wh = e.child_by_field_name("binds")
                            if wh is not None:
                                lines += [lb for lb in (tr.local_bind(b, 6) for b in tr.ordered_binds(kids(wh))) if lb]
                            lines.append(tr.rhs(e, 6, last=(e == eqs[-1])))
                            print(f"  | {tr.pat(p0)} =>\n      " + "\n      ".join(lines))
                    h = tn.replace(".", "_")
                    print(f"instance : IntegralH {tn} := ⟨fun x => (fromEnumH_{h} x : Int), "
                          f"fun i => toEnumH_{h} i.toNat⟩\n")
            except (Unsupported, KeyError, StopIteration) as ex:
                print(f"-- hs2lean: instance {cls} {tn} not translated: {str(ex)[:80]}\n")
    print("/-! ## Newtype instances lifted through non-word fields -/\n")
    for line in data.deferred:
        print(line)
    print("end\nend Sel4Lean.Spec")
    total = len(order) + len(failed) + len(stubs)
    print(f"hs2lean types: {len(order)} translated, {len(failed)} failed, {len(stubs)} unresolved "
          f"({total} types reached)", file=sys.stderr)
    for n, why in sorted(failed.items()):
        print(f"  failed  {n}: {why}", file=sys.stderr)
    for n, why in sorted(stubs.items()):
        print(f"  stubbed {n}: {why}", file=sys.stderr)


# ------------------------------------------------------------------ functions (module mode)

PRELUDE_NAMES = set()  # filled from hs2lean.NAME at runtime

BINDER_FIELDS = {"patterns", "pattern"}


def bound_names(tr, node):
    """Variables bound anywhere inside a function (parameters, lambda/do/case patterns, let/where names)."""
    out, stack = set(), [(node, False)]
    while stack:
        m, binding = stack.pop()
        if m.type == "field_name" and not (m.parent is not None and m.parent.type == "field_pattern"
                                           and len(kids(m.parent)) == 1):
            continue   # a record field label (`C { f = p }`), not a binder; only a pun `C { f }` binds f
        if m.type == "variable" and binding:
            out.add(tr.text(m))
        for i, c in enumerate(m.children):
            if not c.is_named:
                continue
            f = m.field_name_for_child(i)
            b = binding or f in BINDER_FIELDS or (f == "name" and m.type in ("bind", "function"))
            stack.append((c, b))
    return out


def used_names(tr, node):
    """Unqualified variables used under node (`Arch.f` names another module's f, not this one)."""
    out, stack = set(), [node]
    while stack:
        m = stack.pop()
        if m.type == "qualified":
            continue
        if m.type == "variable":
            out.add(tr.text(m))
        stack.extend(m.named_children)
    return out


def sig_stub(tr, name, sig_node, why):
    """`opaque name {a : Type} … : T` from a Haskell signature, or None if the type won't translate."""
    tr.tyvars, tr.constraints, tr.hk = [], [], set()
    try:
        t = tr.ty(sig_node.child_by_field_name("type"))
    except Unsupported:
        return None
    imp = "".join(f" {{{v} : {'Type → Type' if v in tr.hk else 'Type'}}}" for v in tr.tyvars)
    inst = "".join(f" [Inhabited {v}]" for v in tr.tyvars if v not in tr.hk)
    if tr.hk:   # opaque needs an inhabitant: monad-polymorphic results are inhabited via failure
        inst += "".join(f" [Monad {v}] [MonadFailH {v}]" for v in sorted(tr.hk)
                        if ("Monad", v) not in tr.constraints)
    inst += "".join(f" [{c} {v}]" for c, v in tr.constraints)
    return f"-- {why}\nopaque {tr.ident(name)}{imp}{inst} : {t}"


def cmd_module(root, type_roots, modules, namespace="Sel4Lean.Spec", compiled=None):
    from hs2lean import NAME, HEADER as GEN_HEADER
    NAME["fail"] = "failM"   # Spec modules: generic MonadFail (crawl code keeps NondetM-only failH)
    NAME["assert"] = "assertG"
    NAME["runState"] = "runStateND"   # UserMonad is NondetM; see HsPrelude (approximation, TODO W3)
    idx, data, arch_names = cmd_types(root, type_roots, emit=False)
    out_defs, stubs, unresolved, failed = [], {}, {}, {}
    compiled = compiled or set()
    imports, opens, aliases = [], {}, {}   # Lean modules to import; names opened per namespace; arch aliases
    stats = {"translated": 0, "failed": 0}
    local_all = {}
    for mpath in modules:
        src, rn = parse_file(mpath)
        tr = FullTranslator(src, data)
        tr.arch_names = arch_names
        tr.arch_names_all = arch_names
        tr.in_arch_module = ARCH in mpath
        tr.file_types = idx["__file_types__"].get(mpath, set())
        tr.arch_in_scope = arch_scope(mpath, root, idx, arch_names)
        decls = [(n, ns) for n, ns in top_decls(src, rn) if any(d.type in ("function", "bind") for d in ns)]
        local = {n for n, _ in decls}
        tr.local_names = local    # a module's own definitions shadow library name mappings
        local_all.update({n: (tr, ns) for n, ns in decls})
        deps = {}
        for n, ns in decls:
            body = [d for d in ns if d.type != "signature"]
            used = set().union(*(used_names(tr, d) for d in body))
            bound = set().union(*(bound_names(tr, d) for d in body))
            free = used - bound - {n}
            deps[n] = free & local
            closure = import_closure(mpath, root)
            mp = module_paths(root)
            for x in sorted(free - local):
                if x in NAME or x in data.field_type or x in stubs or x in unresolved or x in PROVIDED:
                    continue
                if any(x in opens.get(ns, ()) for ns in opens):
                    continue
                # a definition in an imported module that compiles: use it instead of a stub
                prov = next((hm for hm in closure if hm in mp and lean_module(hm) in compiled
                             and x in module_defs(mp[hm], root)), None)
                if prov is not None:
                    ns = f"Sel4Lean.Spec.M.{lean_module(prov)}"
                    if lean_module(prov) not in imports:
                        imports.append(lean_module(prov))
                    opens.setdefault(ns, set()).add(x)
                    continue
                sig = idx.get("sig:" + x)
                stub = None
                if sig:
                    etr = FullTranslator(sig[0], data)   # resolve names as the declaring file does
                    etr.arch_names, etr.arch_names_all = arch_names, arch_names
                    etr.arch_in_scope = arch_scope(sig[2], root, idx, arch_names)
                    stub = sig_stub(etr, x, sig[1], f"external: {os.path.relpath(sig[2], root)}")
                if stub:
                    stubs[x] = stub
                else:
                    unresolved[x] = "no translatable signature found" if sig else "no signature found"
        # strongly connected components of the local call graph: mutually recursive functions are emitted
        # together in a `mutual` block (as partial defs until W4 adds termination proofs)
        idx_n, low, stk, on, comps, cnt = {}, {}, [], set(), [], [0]

        def scc(v):
            idx_n[v] = low[v] = cnt[0]; cnt[0] += 1
            stk.append(v); on.add(v)
            for w in sorted(deps[v]):
                if w not in idx_n:
                    scc(w); low[v] = min(low[v], low[w])
                elif w in on:
                    low[v] = min(low[v], idx_n[w])
            if low[v] == idx_n[v]:
                c = []
                while True:
                    w = stk.pop(); on.discard(w); c.append(w)
                    if w == v:
                        break
                comps.append(c)
        sys.setrecursionlimit(10000)
        for n, _ in decls:
            if n not in idx_n:
                scc(n)
        order = [n for c in comps for n in c]
        mutual_of = {n: tuple(sorted(c)) for c in comps if len(c) > 1 for n in c}
        body = dict(decls)
        def rhs_names(d):
            """Variables used in right-hand sides and where-clauses (not the defining name or patterns)."""
            out = set()
            for i, c in enumerate(d.children):
                if d.field_name_for_child(i) in ("match", "binds"):
                    out |= used_names(tr, c)
            return out
        recursive = {n for n, ns in decls
                     if n in set().union(*(rhs_names(d) for d in ns if d.type != "signature"))
                     - (set().union(*(bound_names(tr, d) for d in ns if d.type != "signature")) - {n})}
        machine = any(os.path.relpath(mpath, root).startswith(p) for p in MACHINE_INTERFACE)
        for n in order:
            if n in PROVIDED:
                continue   # hand-written in Spec/PSpaceStorable.lean
            override = None
            if ARCH in mpath and not any(d.type == "signature" for d in body[n]) and f"sig:{n}" in idx:
                # an arch function without its own signature: borrow the generic one, read in this file's scope
                gsrc, gsig, gpath = idx[f"sig:{n}"]
                gtr = FullTranslator(gsrc, data)
                gtr.arch_names, gtr.arch_names_all = arch_names, arch_names
                gtr.arch_in_scope = arch_scope(mpath, root, idx, arch_names)
                try:
                    gt = gsig.child_by_field_name("type")
                    if gt.type == "context":
                        gt = gt.child_by_field_name("type")
                    ps = []
                    while gt.type == "function":
                        ps.append(gtr.ty(gt.child_by_field_name("parameter")))
                        gt = gt.child_by_field_name("result")
                    override = (ps, gtr.ty(gt))
                except Unsupported:
                    override = None
            if machine:
                sig = next((d for d in body[n] if d.type == "signature"), None)
                st = sig_stub(tr, n, sig, "machine interface: opaque by design (as l4v MachineOps)") if sig is not None else None
                if st:
                    stubs[n] = st
                    stats["machine"] = stats.get("machine", 0) + 1
                    stats["translated"] += 1
                    continue
            try:
                text = tr.emit_function(n, body[n], sig_override=override)
                if n in mutual_of:
                    recursive.add(n)
                if n in recursive:
                    # TODO(W4): termination proofs (l4v proves them in Isabelle); `partial` hides the body
                    text = text.replace(f"\ndef {tr.ident(n)} ", f"\npartial def {tr.ident(n)} ", 1)
                    stats["partial"] = stats.get("partial", 0) + 1
                out_defs.append((mutual_of.get(n), text))
                stats["translated"] += 1
            except (Unsupported, StopIteration, AttributeError) as ex:
                stats["failed"] += 1
                failed[n] = str(ex)[:120]
                sig = next((d for d in body[n] if d.type == "signature"), None)
                st = sig_stub(tr, n, sig, f"local, not translated: {str(ex)[:80]}") if sig is not None else None
                if st:
                    stubs[n] = st
                else:
                    unresolved[n] = f"local, not translated, no signature: {str(ex)[:60]}"
        # stubs for `Arch.f` calls, from the RISCV64 signature
        closure = import_closure(mpath, root)
        mp = module_paths(root)
        for f in sorted(tr.arch_calls):
            key = f"{ARCH}.{f}"
            if key in stubs or key in aliases:
                continue
            prov = next((hm for hm in closure if ARCH in hm and hm in mp and lean_module(hm) in compiled
                         and f in module_defs(mp[hm], root)), None)
            if prov is not None:   # the real RISCV64 definition, under the name the translation uses
                if lean_module(prov) not in imports:
                    imports.append(lean_module(prov))
                aliases[key] = f"abbrev {key} := @Sel4Lean.Spec.M.{lean_module(prov)}.{tr.ident(f)}"
                continue
            # the arch module may define f without a signature; the generic one has the same shape
            sig = idx.get(f"{ARCH}.sig:{f}") or idx.get(f"sig:{f}")
            st = None
            if sig:
                atr = FullTranslator(sig[0], data)
                atr.arch_names, atr.arch_names_all, atr.in_arch_module = arch_names, arch_names, True
                atr.file_types = idx["__file_types__"].get(sig[2], set())
                atr.arch_in_scope = arch_scope(sig[2], root, idx, arch_names)
                st = sig_stub(atr, key, sig[1], f"arch: {os.path.relpath(sig[2], root)}")
            if st:
                stubs[key] = st
            else:
                unresolved[key] = "no RISCV64 signature"
    print(GEN_HEADER.format(rev="ac4a36d", path=", ".join(os.path.relpath(m, root) for m in modules)))
    print("import Sel4Lean.Spec.PSpaceStorable")
    for im in imports:
        print(f"import Sel4Lean.Spec.Gen.Mod.{im}")
    # Haskell allows overlapping (unreachable) case alternatives; Lean rejects them unless told not to
    print("\nset_option match.ignoreUnusedAlts true")
    print(f"\nnamespace {namespace}\nopen Sel4Lean.Spec\n"
          "open Sel4Lean.Exec (Word PPtr PtrH failH assertH stateAssertH forM_H deleteH)")
    print("noncomputable section\n")
    if opens:
        # imported definitions as local aliases, not `open`: an opened name can clash with Lean's own
        # (`throw`), while a declaration in this namespace takes precedence; `abbrev` stays transparent
        print("/-! ## Definitions from imported modules -/\n")
        for ns, names in sorted(opens.items()):
            for n in sorted(names):
                print(f"abbrev {Translator.ident(n)} := @{ns}.{Translator.ident(n)}")
        print()
    if aliases:
        print("/-! ## RISCV64 definitions from imported modules -/\n")
        for k in sorted(aliases):
            print(aliases[k])
        print()
    print("/-! ## Stubs (from Haskell signatures) -/\n")
    for n in sorted(stubs):
        print(stubs[n]); print()
    if unresolved:
        print("/-! ## Unresolved (no stub possible)")
        for n, why in sorted(unresolved.items()):
            print(f"  {n}: {why}")
        print("-/\n")
    print("/-! ## Translated -/\n")
    i = 0
    while i < len(out_defs):
        grp, text = out_defs[i]
        if grp is None:
            print(text); print(); i += 1
            continue
        block = []
        while i < len(out_defs) and out_defs[i][0] == grp:
            block.append(out_defs[i][1]); i += 1
        print(f"-- mutually recursive: {', '.join(grp)}")
        print("mutual")
        for t in block:
            print(t); print()
        print("end\n")
    print(f"end\nend {namespace}")
    total = stats["translated"] + stats["failed"]
    print(f"hs2lean imports: {len(imports)} modules, {sum(len(v) for v in opens.values())} names, "
          f"{len(aliases)} arch aliases", file=sys.stderr)
    print(f"hs2lean module: {stats['translated']}/{total} functions translated "
          f"({stats.get('partial', 0)} partial, {stats.get('machine', 0)} machine-opaque), "
          f"{len([k for k in stubs if k not in failed])} external stubs, {len(unresolved)} unresolved", file=sys.stderr)
    for n, why in sorted(failed.items()):
        print(f"  failed {n}: {why}", file=sys.stderr)
    for n, why in sorted(unresolved.items()):
        print(f"  unresolved {n}: {why}", file=sys.stderr)


if __name__ == "__main__":
    try:
        if sys.argv[1] == "order":   # order ROOT FILE...: dependency order
            for f in dependency_order(sys.argv[2], sys.argv[3:]):
                print(os.path.relpath(f, sys.argv[2]))
        elif sys.argv[1] == "types":
            cmd_types(sys.argv[2], sys.argv[3:])
        elif sys.argv[1] == "module":
            # module ROOT --types F... --modules M...
            a = sys.argv[3:]
            i, j = a.index("--types"), a.index("--modules")
            if "--gen-dir" in a:
                g = a.index("--gen-dir")
                globals()["GEN_DIR"] = a[g + 1]
                del a[g:g + 2]
            comp = set()
            if "--compiled" in a:
                c = a.index("--compiled")
                comp = {l.split()[1] for l in open(a[c + 1]) if l.startswith("✔")}
                del a[c:c + 2]
            k = a.index("--namespace") if "--namespace" in a else None
            mods = a[j + 1:k] if k else a[j + 1:]
            cmd_module(sys.argv[2], a[i + 1:j], mods, a[k + 1] if k else "Sel4Lean.Spec", comp)
        else:
            raise SystemExit(__doc__)
    except Unsupported as ex:
        print(f"hs2lean: {ex}", file=sys.stderr)
        sys.exit(2)
