"""Lean <-> Isabelle gate: check the Lean spec against l4v's built Isabelle executable spec (session ExecSpec).

    isagate.py gen W3DIR CONSTS        writes W3DIR/isabelle/Values.thy from W3DIR/cases.tsv (the difftest cases),
                                       each case mapped to its ExecSpec constant (CONSTS = consts.tsv)
    isagate.py compare W3DIR           Isabelle values (isabelle/values.tsv) vs Lean (lean.out), Haskell for
                                       reference (hs.out): writes isabelle/values-compare.tsv
    isagate.py names CONSTS LEAN OUT   name-level correspondence: ExecSpec constants vs Lean declarations

The oracle is Isabelle itself: `Value_Command.value` on the design spec as l4v builds it (spec/design,
generated by l4v's own translator from the same Haskell, plus its hand-written skeleton parts).
"""
import os
import re
import sys

import difftest

# Isabelle-generated helper constants: not spec definitions
HELPER = re.compile(r"(_update$|_ext$|\.make$|\.extend$|\.truncate$|\.fields$|\.fields_def|^Abs_|^Rep_|"
                    r"\.(case|rec|size|pred|rel|set|map|equal|discI|sel)_|\.Abs_|\.Rep_|\.case_|\.rec_|\.size_|"
                    r"\.pred_|\.rel_|\.set_|\.map_|_class\.|\.dummy_|\.Rep|\.Abs|_rep$|_abs$|\.typedef|"
                    r"\.term_of_|\.typerep_|\.enum_|\.less_eq_|\.less_|\.equal_|\.default_|\.zero_|\.one_|"
                    r"\.plus_|\.minus_|\.times_|\.divide_|\.modulo_|\.uminus_|\.ord_|\.linorder_|\.bot_|\.top_)")


def base(name):
    return name.split(".")[-1]


def load_consts(path):
    out = []
    for line in open(path):
        parts = line.rstrip("\n").split("\t")
        if len(parts) >= 3:
            out.append((parts[0], parts[1], parts[2]))
    return out


def resolve(lean_module, fn, consts):
    """The ExecSpec constant for Lean function fn of module lean_module, or None."""
    cands = [c for c in consts if base(c[0]) == fn and not HELPER.search(c[0])]
    if not cands:
        return None
    arch = "RISCV64" in lean_module
    pref = [c for c in cands if ("RISCV64" in c[0]) == arch] or cands
    # a declaration (`…Decls_H`) and its definition share the constant; any one will do
    # prefer a monomorphic constant (the Haskell function at its type) over a polymorphic abbreviation
    # (e.g. Hardware_H's `fromPAddr :: 64 word ⇒ 64 word` over Platform's `fromPAddr == id`)
    return sorted(pref, key=lambda c: ("'" in c[2], len(c[0])))[0][0]


def cmd_gen(w3, consts_path):
    consts = load_consts(consts_path)
    cases = [l.rstrip("\n").split("\t") for l in open(os.path.join(w3, "cases.tsv"))][1:]
    rows, unmapped = [], set()
    for cid, lm, fn, ty, args in cases:
        c = resolve(lm, fn, consts)
        if c is None:
            unmapped.add(f"{lm}.{fn}")
            continue
        kinds = [p.strip() for p in ty.split("->")][:-1]
        vals = args.split() if args else []
        ml_args = []
        for k, v in zip(kinds, vals):
            ml_args.append(("B " + ("true" if v == "True" else "false")) if k == "Bool" else f"N {int(v)}")
        rows.append(f'("{cid}", "{c}", [{", ".join(ml_args)}])')
    os.makedirs(os.path.join(w3, "isabelle"), exist_ok=True)
    thy = VALUES_THY.replace("@@CASES@@", ",\n   ".join(rows))
    open(os.path.join(w3, "isabelle", "Values.thy"), "w").write(thy)
    print(f"isagate gen: {len(rows)} cases mapped, {len(unmapped)} functions without an ExecSpec constant")
    for u in sorted(unmapped):
        print("  unmapped", u)


VALUES_THY = r'''theory Values
  imports ExecSpec.API_H ExecSpec.ArchIntermediate_H
begin

text \<open>Evaluate the differential-test cases in l4v's executable spec. Each case is a constant applied to
numerals (built as typed terms, not parsed) and evaluated with Isabelle's @{command value} machinery.
Generated by tools/hs2lean/isagate.py. Output: GATE_OUT/values.tsv\<close>

ML \<open>
  datatype arg = N of int | B of bool
  val out = Path.explode (getenv "GATE_OUT") + Path.basic "values.tsv"
  val ctxt = @{context}
  val thy = @{theory}
  fun mono T = Term.map_atyps (fn _ => @{typ unit}) T
  fun mk_arg T (N n) = HOLogic.mk_number T n
    | mk_arg _ (B b) = if b then @{term True} else @{term False}
  fun plain t = Print_Mode.setmp [] (fn () => Syntax.string_of_term ctxt t) ()
                |> String.translate (fn #"\n" => " " | c => str c)
  (* l4v defines spec constants with `defs` (no code equations): unfold them with their definitional
     axioms (a theorem-producing rewrite), then evaluate the remaining arithmetic *)
  val space = Consts.space_of (Sign.consts_of thy)
  (* only the spec's own constants: unfolding Word_Lib's definitions (word +, shifts) would leave the
     code generator's representation and blow up *)
  fun spec_const c = String.isPrefix "ExecSpec." (#theory_long_name (Name_Space.the_entry space c))
                     handle ERROR _ => false
  val def_tab =
    fold (fn (_, th) => fn tab =>
        (case Thm.prop_of th of
          Const (@{const_name Pure.eq}, _) $ lhs $ _ =>
            (case head_of lhs of
              Const (c, _) => if spec_const c then Symtab.cons_list (c, th) tab else tab
            | _ => tab)
        | _ => tab))
      (Thm.all_axioms_of thy) Symtab.empty
  fun consts_in t = Term.fold_aterms (fn Const (c, _) => insert (op =) c | _ => I) t []
  fun unfold t n =
    let
      val defs = maps (Symtab.lookup_list def_tab) (consts_in t)
    in
      if null defs orelse n = 0 then t
      else
        let
          val ctxt' = put_simpset HOL_basic_ss ctxt addsimps defs
          val t' = Thm.rhs_of (Simplifier.rewrite ctxt' (Thm.cterm_of ctxt t)) |> Thm.term_of
        in if t' aconv t then t else unfold t' (n - 1) end
    end
  fun eval1 (c, args) =
    let
      (* an abbreviation (e.g. Platform's `fromPAddr == id`) is not a logical constant: use its rhs *)
      val (T, head) =
        (case try (Consts.the_abbreviation (Sign.consts_of thy)) c of
          SOME (ty, rhs) => (mono ty, Term.map_types mono rhs)
        | NONE => let val ty = mono (Sign.the_const_type thy c) in (ty, Const (c, ty)) end)
      val t = list_comb (head, map2 mk_arg (take (length args) (binder_types T)) args)
      val value = Timeout.apply (Time.fromSeconds 30) (Value_Command.value ctxt)
      (* the default simpset (Word_Lib's lemmas): e.g. `finiteBitSize (undefined :: 64 word) = 64`, which
         code evaluation cannot do (it evaluates `undefined` strictly) *)
      fun simp u = Thm.rhs_of (Timeout.apply (Time.fromSeconds 30)
                     (Simplifier.rewrite (ctxt addsimps @{thms word_size})) (Thm.cterm_of ctxt u)) |> Thm.term_of
      fun numeral u = can HOLogic.dest_number u orelse u aconv @{term True} orelse u aconv @{term False}
    in
      (case Exn.result value t of
        Exn.Res v => plain v
      | Exn.Exn _ =>
          let val u = unfold t 12 in
            (case Exn.result value u of
              Exn.Res v => plain v
            | Exn.Exn _ => let val w = simp u in if numeral w then plain w else plain (value w) end)
          end)
    end
  (* Exn.result: catches evaluation failures but lets interrupts through *)
  fun ev (id, c, args) =
    (case Exn.result eval1 (c, args) of
      Exn.Res r => id ^ "\t" ^ r
    | Exn.Exn e => id ^ "\tERR " ^ hd (split_lines (Runtime.exn_message e) @ [""]))
  val cases = [
   @@CASES@@]
  val _ = File.write out (cat_lines (map ev cases) ^ "\n")
  val _ = writeln ("GATE values: " ^ string_of_int (length cases))
\<close>

end
'''


def parse_isa(s):
    s = s.strip()
    if s == "True":
        return 1
    if s == "False":
        return 0
    m = re.fullmatch(r"(-\s*)?(0x[0-9A-Fa-f]+|\d+)", s)
    if m:
        v = int(m.group(2), 0)
        return -v if m.group(1) else v
    return None


def cmd_compare(w3):
    cases = {l.split("\t")[0]: l.rstrip("\n").split("\t") for l in list(open(os.path.join(w3, "cases.tsv")))[1:]}
    isa = {}
    for line in open(os.path.join(w3, "isabelle", "values.tsv")):
        parts = line.rstrip("\n").split("\t", 1)
        if len(parts) == 2:
            isa[parts[0]] = parts[1]
    lean = difftest.parse_out(os.path.join(w3, "lean.out"))
    hs = difftest.parse_out(os.path.join(w3, "hs.out"))
    stats, per_fn = {}, {}
    with open(os.path.join(w3, "isabelle", "values-compare.tsv"), "w") as f:
        f.write("id\tmodule\tfunction\targs\tisabelle\tlean\thaskell\tverdict\n")
        for cid, (_, lm, fn, ty, args) in sorted(cases.items(), key=lambda kv: int(kv[0])):
            raw = isa.get(cid)
            iv = parse_isa(raw) if raw is not None else None
            lv = lean.get(int(cid))
            if raw is None:
                v = "no-isabelle-constant"
            elif iv is None and "undefined" in raw and hs.get(int(cid)) == "error":
                v = "both-undefined"            # Isabelle `undefined`, Haskell `error`: Lean's `undefinedH`
            elif iv is None:
                v = "isabelle-unevaluated"     # ERR/EXN, or a symbolic result (e.g. `undefined`)
            elif lv is None:
                v = "lean-missing"
            else:
                v = "agree" if iv == lv else "DIFFER"
            stats[v] = stats.get(v, 0) + 1
            per_fn.setdefault(f"{lm}.{fn}", []).append(v)
            f.write(f"{cid}\t{lm}\t{fn}\t{args}\t{raw}\t{lv}\t{hs.get(int(cid))}\t{v}\n")
    print("isagate: " + ", ".join(f"{k} {v}" for k, v in sorted(stats.items())))
    for fn, vs in sorted(per_fn.items()):
        bad = [v for v in vs if v not in ("agree", "both-undefined")]
        if bad:
            print(f"  {fn}: {len(bad)}/{len(vs)} {sorted(set(bad))}")
    ok = sum(1 for vs in per_fn.values() if all(v in ("agree", "both-undefined") for v in vs))
    print(f"isagate: {ok}/{len(per_fn)} functions agree with Isabelle on every case")


def cmd_names(consts_path, lean_path, out):
    consts = [c for c in load_consts(consts_path) if not HELPER.search(c[0])]
    lean = {}
    for line in open(lean_path):
        parts = line.rstrip("\n").split("\t")
        if parts and parts[0]:
            lean.setdefault(base(parts[0]), []).append(parts[0])
    isa_bases = {}
    for c in consts:
        isa_bases.setdefault(base(c[0]), []).append(c)
    by_thy = {}
    with open(out, "w") as f:
        f.write("isabelle\ttheory\tlean\n")
        for c in consts:
            hit = lean.get(base(c[0]))
            by_thy.setdefault(c[1], [0, 0])
            by_thy[c[1]][1] += 1
            if hit:
                by_thy[c[1]][0] += 1
            f.write(f"{c[0]}\t{c[1]}\t{(hit or [''])[0]}\n")
    have = sum(v[0] for v in by_thy.values())
    total = sum(v[1] for v in by_thy.values())
    print(f"isagate names: {have}/{total} ExecSpec constants have a Lean declaration of the same name")
    for thy, (h, t) in sorted(by_thy.items(), key=lambda kv: kv[1][0] - kv[1][1]):
        if h < t:
            print(f"  {thy}: {h}/{t}")
    lean_only = sorted(b for b in lean if b not in isa_bases)
    print(f"isagate names: {len(lean_only)} Lean names with no ExecSpec constant")


if __name__ == "__main__":
    cmd = sys.argv[1]
    if cmd == "gen":
        cmd_gen(sys.argv[2], sys.argv[3])
    elif cmd == "compare":
        cmd_compare(sys.argv[2])
    elif cmd == "names":
        cmd_names(sys.argv[2], sys.argv[3], sys.argv[4])
    else:
        raise SystemExit(__doc__)
