"""Generate Lean from l4v's spec/machine/RISCV64/Kernel_Config.thy (the build configuration l4v verifies).

    kconfig.py KERNEL_CONFIG_THY > lean/Sel4Lean/Spec/Gen/KernelConfig.lean

Every `definition X :: T where "X ≡ V"` (T: nat, machine_word, bool; or untyped numeral) becomes
`def X : T' := V` with the same name, so the Lean values come from the l4v artifact, not a copy.
"""
import re
import sys

TYPES = {"nat": "Nat", "machine_word": "Word", "bool": "Bool", None: "Nat"}

DEF = re.compile(r'definition\s+(\w+)\s*(?:::\s*"?([\w ]+?)"?)?\s+where\s*(?:\(\*.*?\*\)\s*)?"\s*\1\s*\\<equiv>\s*([^"]+?)"',
                 re.S)


def main(path):
    src = open(path).read()
    print("/-\n  GENERATED by tools/hs2lean/kconfig.py from l4v's spec/machine/RISCV64/Kernel_Config.thy.\n"
          "  SPDX-License-Identifier: GPL-2.0-only (derived from seL4/l4v, https://github.com/seL4/l4v)\n"
          "  Do not edit by hand; regenerate with env/remote/hs2lean.sh.\n-/\n")
    print("import Sel4Lean.Exec.Prelude\n\n/-! l4v's verified RISCV64 build configuration (names as in Isabelle). -/\n")
    print("namespace Sel4Lean.Spec.KernelConfig\nopen Sel4Lean.Exec (Word)\n")
    n = 0
    for m in DEF.finditer(src):
        name, ty, val = m.group(1), (m.group(2) or "").strip() or None, m.group(3).strip()
        lt = TYPES.get(ty)
        if lt is None:
            print(f"-- skipped {name} :: {ty}")
            continue
        if val in ("True", "False"):
            val = val.lower()
        elif not re.fullmatch(r"(0x[0-9A-Fa-f]+|\d+)", val):
            print(f"-- skipped {name} ≡ {val}")
            continue
        print(f"/-- `{name} ≡ {m.group(3).strip()}` -/\ndef {name} : {lt} := {val}")
        n += 1
    print("\nend Sel4Lean.Spec.KernelConfig")
    print(f"kconfig: {n} definitions", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1])
